<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.RSpecAdapter\Gallio.RSpecAdapter$(ProjectVariant).csproj" />
    
    <CSharpProject Include="Gallio.RSpecAdapter.Tests\Gallio.RSpecAdapter.Tests$(ProjectVariant).csproj" />    
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.RSpecAdapter\bin\Gallio.RSpecAdapter.dll">
      <Folder>RSpec</Folder>
    </Binary>
    <PluginFile Include="Gallio.RSpecAdapter\Gallio.RSpecAdapter.plugin">
      <Folder>RSpec</Folder>
    </PluginFile>
    
    <TestAssembly Include="Gallio.RSpecAdapter.Tests\bin\Gallio.RSpecAdapter.Tests.dll" />

    <Feature Include="FEATURE_RSPEC_ADAPTER" />
  </ItemGroup>
  
  <Target Name="AfterImage">
    <RemoveDir Directories="$(ImageDir)\bin\RSpec\libs" />
    <MakeDir Directories="$(ImageDir)\bin\RSpec" />
  
    <SvnExport RepositoryPath="$(ModuleDir)\libs"
               LocalPath="$(ImageDir)\bin\RSpec\libs" />
			   
    <RemoveDir Directories="$(ImageDir)\bin\RSpec\Scripts" />
    <MakeDir Directories="$(ImageDir)\bin\RSpec" />
  
    <SvnExport RepositoryPath="$(ModuleDir)\Gallio.RSpecAdapter\Scripts"
               LocalPath="$(ImageDir)\bin\RSpec\Scripts" />

    <ItemGroup>
      <LibsFiles Include="$(ImageDir)\bin\RSpec\libs\**\*" />
      <ScriptsFiles Include="$(ImageDir)\bin\RSpec\scripts\**\*" />

      <Token Include="LibsFilesToken">
        <ReplacementValue>@(LibsFiles->'&lt;file path="libs\%(RecursiveDir)%(Filename)%(Extension)"/&gt;', '%0A    ')</ReplacementValue>
      </Token>
      <Token Include="ScriptsFilesToken">
        <ReplacementValue>@(ScriptsFiles->'&lt;file path="scripts\%(RecursiveDir)%(Filename)%(Extension)"/&gt;', '%0A    ')</ReplacementValue>
      </Token>
    </ItemGroup>

    <TemplateFile Template="$(ImageDir)\bin\RSpec\Gallio.RSpecAdapter.plugin"
		  Tokens="@(Token)" />
    <Delete Files="$(ImageDir)\bin\RSpec\Gallio.RSpecAdapter.plugin" />
    <Move SourceFiles="$(ImageDir)\bin\RSpec\Gallio.RSpecAdapter.out"
          DestinationFiles="$(ImageDir)\bin\RSpec\Gallio.RSpecAdapter.plugin" />
  </Target>
  
  <Target Name="BeforeDist">
    <Exec Command="&quot;$(ToolsDir)\Wix\heat.exe&quot; dir &quot;$(ImageDir)\bin\RSpec\libs&quot; -cg ComponentGroup -var var.RSpec.libs.source -gg -ke -nologo -sfrag -sreg -t:RSpec-libs.xslt -out RSpec-libs.wxi" />
    <Exec Command="&quot;$(ToolsDir)\Wix\heat.exe&quot; dir &quot;$(ImageDir)\bin\RSpec\Scripts&quot; -cg ComponentGroup -var var.RSpec.scripts.source -gg -ke -nologo -sfrag -sreg -t:RSpec-scripts.xslt -out RSpec-scripts.wxi" />
  </Target>
</Project>
