//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbUnit.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MbUnit.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SolarSystem&gt;
        ///  &lt;Planets&gt;
        ///    &lt;Planet name=&apos;Mercury&apos; distanceToSun=&apos;0.4 AU&apos;&gt;
        ///      &lt;Satellites/&gt;
        ///    &lt;/Planet&gt;
        ///    &lt;Planet name=&apos;Venus&apos; distanceToSun=&apos;0.7 AU&apos;&gt;
        ///      &lt;Satellites/&gt;
        ///    &lt;/Planet&gt;
        ///    &lt;!-- Hey! This one is mine! --&gt;
        ///    &lt;Planet name=&apos;Earth&apos; distanceToSun=&apos;1 AU&apos;&gt;
        ///      &lt;Satellites&gt;
        ///        &lt;Satellite name=&apos;Moon&apos;/&gt;
        ///      &lt;/Satellites&gt;
        ///    &lt;/Planet&gt;
        ///     &lt;Planet name=&apos;Mars&apos; distanceToSun=&apos;1.5 AU&apos;&gt;
        ///      &lt;Satellites&gt;
        ///        &lt;Satellite name=&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SolarSystem {
            get {
                return ResourceManager.GetString("SolarSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;xs:schema attributeFormDefault=&apos;unqualified&apos; elementFormDefault=&apos;qualified&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xs:element name=&apos;SolarSystem&apos;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&apos;Planets&apos;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element maxOccurs=&apos;unbounded&apos; name=&apos;Planet&apos;&gt;
        ///                &lt;xs:complexType&gt;
        ///                  &lt;xs:sequence&gt;
        ///                    &lt;xs:element name=&apos;Satellites [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SolarSystemSchema {
            get {
                return ResourceManager.GetString("SolarSystemSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SolarSystem&gt;
        ///  &lt;Planets&gt;
        ///    &lt;Planet name=&apos;Mercury&apos; distanceToSun=&apos;0.4 AU&apos;&gt;
        ///      &lt;Satellites/&gt;
        ///    &lt;/Planet&gt;
        ///    &lt;Planet name=&apos;Venus&apos; distanceToSun=&apos;0.7 AU&apos;&gt;
        ///      &lt;Satellites/&gt;
        ///    &lt;/Planet&gt;
        ///    &lt;!-- Hey! This one is yours! --&gt;
        ///    &lt;Planet name=&apos;Earth&apos; distanceToSun=&apos;1 AU&apos;&gt;
        ///      &lt;Satellites&gt;
        ///        &lt;Satellite name=&apos;Moon&apos;/&gt;
        ///      &lt;/Satellites&gt;
        ///    &lt;/Planet&gt;
        ///     &lt;Planet name=&apos;Mars&apos; distanceToSun=&apos;1.666 AU&apos;&gt;
        ///      &lt;Satellites&gt;
        ///        &lt;Satellite nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SolarSystemWithErrors {
            get {
                return ResourceManager.GetString("SolarSystemWithErrors", resourceCulture);
            }
        }
    }
}
