<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <PropertyGroup>
    <MonoCompatible>false</MonoCompatible>
  </PropertyGroup>
  
  <ItemGroup>
    <CSharpProject Include="Gallio.Navigator\Gallio.Navigator$(ProjectVariant).csproj" />

    <CSharpProject Include="Gallio.Navigator.Tests\Gallio.Navigator.Tests$(ProjectVariant).csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.Navigator\bin\Gallio.Navigator.exe">
        <Folder>Navigator</Folder>
    </Binary>
    <Binary Include="Gallio.Navigator\bin\Gallio.VisualStudio.Interop.dll">
        <Folder>Navigator</Folder>
    </Binary>
    <Binary Include="Gallio.Navigator\Gallio.Navigator.exe.config">
        <Folder>Navigator</Folder>
    </Binary>
    <Binary Include="Gallio.Navigator\Readme.txt">
        <Folder>Navigator</Folder>
    </Binary>
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.Navigator.Tests\bin\Gallio.Navigator.Tests.dll" />
  </ItemGroup>
</Project>
