<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.Ambience\Gallio.Ambience.csproj" />
    <CSharpProject Include="Gallio.Ambience.Server\Gallio.Ambience.Server.csproj" />
    <CSharpProject Include="Gallio.Ambience.Tests\Gallio.Ambience.Tests.csproj" />    
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.Ambience.Server\bin\Gallio.Ambience.Server.exe" />
    <Binary Include="Gallio.Ambience.Server\bin\Gallio.Ambience.Server.exe.config" />

    <Content Include="libs\db4o.license.html" />
    <Content Include="libs\Cecil.FlowAnalysis.license.html" />
    <Content Include="libs\Mono.GetOptions.license.html" />
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.Ambience.Tests\bin\Gallio.Ambience.Tests.dll" />

    <DocumentedAssembly Include="Gallio.Ambience\bin\Gallio.Ambience.dll" />
    
    <Feature Include="FEATURE_AMBIENCE" />
  </ItemGroup>

  <Target Name="AfterImage">
    <Message Text="Running ILMerge on Gallio.Ambience.dll..."
             Importance="High" />

    <Exec Command="&quot;$(ToolsDir)\ILMerge\ILMerge.exe&quot; &quot;Gallio.Ambience\bin\Gallio.Ambience.dll&quot; &quot;Gallio.Ambience\bin\Db4objects.Db4o.dll&quot; &quot;Gallio.Ambience\bin\Db4objects.Db4o.Linq.dll&quot; &quot;Gallio.Ambience\bin\Cecil.FlowAnalysis.dll&quot; &quot;Gallio.Ambience\bin\Mono.Cecil.dll&quot; /internalize &quot;/out:$(ImageDir)\bin\Gallio.Ambience.dll&quot; &quot;/keyfile:$(SourceDir)\Key.snk&quot;" />
  </Target>  
</Project>
