<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.NAntTasks\Gallio.NAntTasks$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.NAntTasks.Tests\Gallio.NAntTasks.Tests$(ProjectVariant).csproj" />
  </ItemGroup>

  <ItemGroup>
    <DocumentedAssembly Include="Gallio.NAntTasks\bin\Gallio.NAntTasks.dll" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.NAntTasks\bin\Gallio.NAntTasks.dll" />
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.NAntTasks.Tests\bin\Gallio.NAntTasks.Tests.dll" />
  </ItemGroup>
</Project>
