<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  <Import Project="Pex.targets" />

  <PropertyGroup>
    <MonoCompatible>false</MonoCompatible>
  </PropertyGroup>
  
  <ItemGroup>
    <CSharpProject Include="MbUnit.Pex\MbUnit.Pex.csproj" />

    <CSharpProject Include="MbUnit.Pex.TestResources\MbUnit.Pex.TestResources.csproj" />
    <CSharpProject Include="MbUnit.Pex.Tests\MbUnit.Pex.Tests.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$(PexInstalled)">
    <Binary Include="MbUnit.Pex\bin\MbUnit.Pex.dll" />

    <TestAssembly Include="MbUnit.Pex.Tests\bin\MbUnit.Pex.Tests.dll" />

    <Feature Include="FEATURE_MBUNIT_PEX" />
  </ItemGroup>
</Project>
