<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />

  <ItemGroup>
    <CSharpProject Include="Gallio.CSUnitAdapter\Gallio.CSUnitAdapter$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.CSUnitAdapter.Tests\Gallio.CSUnitAdapter.Tests$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.CSUnitAdapter.TestResources\Gallio.CSUnitAdapter.TestResources$(ProjectVariant).csproj" />
    
    <AssemblyFile Include="Gallio.CSUnitAdapter\bin\Gallio.CSUnitAdapter.dll">
      <ImagePath>bin\CSUnit</ImagePath>
    </AssemblyFile>
    <PluginFile Include="Gallio.CSUnitAdapter\Gallio.CSUnitAdapter.plugin">
      <ImagePath>bin\CSUnit</ImagePath>
    </PluginFile>
    <File Include="Gallio.CSUnitAdapter\Readme.txt">
      <ImagePath>bin\CSUnit</ImagePath>
    </File>
    <File Include="Gallio.CSUnitAdapter\csUnit.dll.tdnet">
      <ImagePath>bin\CSUnit</ImagePath>
    </File>
    <File Include="Gallio.CSUnitAdapter\Resources\csUnit.ico">
      <ImagePath>bin\CSUnit\Resources</ImagePath>
    </File>    
    
    <File Include="libs\csUnit.dll">
      <ImagePath>bin\CSUnit</ImagePath>
    </File>
    <File Include="libs\csUnit.Common.dll">
      <ImagePath>bin\CSUnit</ImagePath>
    </File>
    <File Include="libs\csUnit.Core.dll">
      <ImagePath>bin\CSUnit</ImagePath>
    </File>
    <File Include="libs\csUnit.Interfaces.dll">
      <ImagePath>bin\CSUnit</ImagePath>
    </File>
    <File Include="libs\license.txt">
      <ImagePath>bin\CSUnit</ImagePath>
    </File>
    
    <TestAssembly Include="Gallio.CSUnitAdapter.Tests\bin\Gallio.CSUnitAdapter.Tests.dll" />
  </ItemGroup>
</Project>
