<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <ItemGroup>
    <CSharpProject Include="Gallio.CSUnitAdapter\Gallio.CSUnitAdapter$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.CSUnitAdapter.Tests\Gallio.CSUnitAdapter.Tests$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.CSUnitAdapter.TestResources\Gallio.CSUnitAdapter.TestResources$(ProjectVariant).csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.CSUnitAdapter\bin\Gallio.CSUnitAdapter.dll">
        <Folder>CSUnit</Folder>
    </Binary>
    <PluginFile Include="Gallio.CSUnitAdapter\Gallio.CSUnitAdapter.plugin">
        <Folder>CSUnit</Folder>
    </PluginFile>
    <Binary Include="Gallio.CSUnitAdapter\Readme.txt">
        <Folder>CSUnit</Folder>
    </Binary>
    <Binary Include="libs\csUnit.dll">
        <Folder>CSUnit</Folder>
    </Binary>
    <Binary Include="libs\csUnit.Common.dll">
        <Folder>CSUnit</Folder>
    </Binary>
    <Binary Include="libs\csUnit.Core.dll">
        <Folder>CSUnit</Folder>
    </Binary>
    <Binary Include="libs\csUnit.Interfaces.dll">
        <Folder>CSUnit</Folder>
    </Binary>
    <Binary Include="libs\license.txt">
        <Folder>CSUnit</Folder>
    </Binary>
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.CSUnitAdapter.Tests\bin\Gallio.CSUnitAdapter.Tests.dll" />
  </ItemGroup>
</Project>
