<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(RootDir)\Module.targets" />

  <ItemGroup>
    <NestedModule Include="src\All.module" />
  </ItemGroup>

  <ItemGroup>
    <File Include="Gallio License.txt" />
    <File Include="Release Notes.txt" />
    <File Include="ASL - Apache Software Foundation License.txt" />

    <Extra Include="$(LibsDir)\H2Reg\H2Reg.*">
      <Folder>H2Reg</Folder>
    </Extra>
  </ItemGroup>  
</Project>
