<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <!-- C# Test Project -->
  <ItemGroup>
    <TemplateFile Include="MbUnit.TestProjectTemplate.CSharp.csproj">
      <Base>MbUnit.TestProjectTemplate.CSharp</Base>
      <Zip>VS2005\ProjectTemplates\CSharp\Test\MbUnit3.TestProjectTemplate.CSharp.zip</Zip>
    </TemplateFile>
    <TemplateFile Include="Template.vstemplate">
      <Base>MbUnit.TestProjectTemplate.CSharp</Base>
      <Zip>VS2005\ProjectTemplates\CSharp\Test\MbUnit3.TestProjectTemplate.CSharp.zip</Zip>
    </TemplateFile>
    <TemplateFile Include="Template.ico">
      <Base>MbUnit.TestProjectTemplate.CSharp</Base>
      <Zip>VS2005\ProjectTemplates\CSharp\Test\MbUnit3.TestProjectTemplate.CSharp.zip</Zip>
    </TemplateFile>
    <TemplateFile Include="Properties\AssemblyInfo.cs">
      <Base>MbUnit.TestProjectTemplate.CSharp</Base>
      <Zip>VS2005\ProjectTemplates\CSharp\Test\MbUnit3.TestProjectTemplate.CSharp.zip</Zip>
    </TemplateFile>
  </ItemGroup>

  <!-- VB Test Project -->
  <ItemGroup>
    <TemplateFile Include="MbUnit.TestProjectTemplate.VisualBasic.vbproj">
      <Base>MbUnit.TestProjectTemplate.VisualBasic</Base>
      <Zip>VS2005\ProjectTemplates\VisualBasic\Test\MbUnit3.TestProjectTemplate.VisualBasic.zip</Zip>
    </TemplateFile>
    <TemplateFile Include="Template.vstemplate">
      <Base>MbUnit.TestProjectTemplate.VisualBasic</Base>
      <Zip>VS2005\ProjectTemplates\VisualBasic\Test\MbUnit3.TestProjectTemplate.VisualBasic.zip</Zip>
    </TemplateFile>
    <TemplateFile Include="Template.ico">
      <Base>MbUnit.TestProjectTemplate.VisualBasic</Base>
      <Zip>VS2005\ProjectTemplates\VisualBasic\Test\MbUnit3.TestProjectTemplate.VisualBasic.zip</Zip>
    </TemplateFile>
    <TemplateFile Include="My Project\AssemblyInfo.vb">
      <Base>MbUnit.TestProjectTemplate.VisualBasic</Base>
      <Zip>VS2005\ProjectTemplates\VisualBasic\Test\MbUnit3.TestProjectTemplate.VisualBasic.zip</Zip>
    </TemplateFile>
  </ItemGroup>

  <!-- C# Test Fixture -->
  <ItemGroup>
    <TemplateFile Include="TestFixture.cs">
      <Base>MbUnit.ItemTemplates.CSharp</Base>
      <Zip>VS2005\ItemTemplates\CSharp\Test\MbUnit3.TestFixtureTemplate.CSharp.zip</Zip>
    </TemplateFile>
    <TemplateFile Include="TestFixture.vstemplate">
      <Base>MbUnit.ItemTemplates.CSharp</Base>
      <Zip>VS2005\ItemTemplates\CSharp\Test\MbUnit3.TestFixtureTemplate.CSharp.zip</Zip>
    </TemplateFile>
    <TemplateFile Include="Template.ico">
      <Base>MbUnit.ItemTemplates.CSharp</Base>
      <Zip>VS2005\ItemTemplates\CSharp\Test\MbUnit3.TestFixtureTemplate.CSharp.zip</Zip>
    </TemplateFile>
  </ItemGroup>

  <!-- VB Test Fixture -->
  <ItemGroup>
    <TemplateFile Include="TestFixture.vb">
      <Base>MbUnit.ItemTemplates.VisualBasic</Base>
      <Zip>VS2005\ItemTemplates\VisualBasic\Test\MbUnit3.TestFixtureTemplate.VisualBasic.zip</Zip>
    </TemplateFile>
    <TemplateFile Include="TestFixture.vstemplate">
      <Base>MbUnit.ItemTemplates.VisualBasic</Base>
      <Zip>VS2005\ItemTemplates\VisualBasic\Test\MbUnit3.TestFixtureTemplate.VisualBasic.zip</Zip>
    </TemplateFile>
    <TemplateFile Include="Template.ico">
      <Base>MbUnit.ItemTemplates.VisualBasic</Base>
      <Zip>VS2005\ItemTemplates\VisualBasic\Test\MbUnit3.TestFixtureTemplate.VisualBasic.zip</Zip>
    </TemplateFile>
  </ItemGroup>
</Project>
