<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <PropertyGroup>
    <MonoCompatible>false</MonoCompatible>
  </PropertyGroup>
  
  <ItemGroup>
    <CSharpProject Include="Gallio.NCoverIntegration\Gallio.NCoverIntegration$(ProjectVariant).csproj" />

    <CSharpProject Include="Gallio.NCoverIntegration.Tests\Gallio.NCoverIntegration.Tests$(ProjectVariant).csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.NCoverIntegration\bin\Gallio.NCoverIntegration.dll">
        <Folder>NCover</Folder>
    </Binary>
    <PluginFile Include="Gallio.NCoverIntegration\Gallio.NCoverIntegration.plugin">
        <Folder>NCover</Folder>
    </PluginFile>

    <Binary Include="libs\NCover Readme.txt">
        <Folder>NCover\libs</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer Readme.txt">
        <Folder>NCover\libs</Folder>
    </Binary>

    <Binary Include="libs\NCover\Coverage.xsl">
        <Folder>NCover\libs\NCover</Folder>
    </Binary>
    <Binary Include="libs\NCover\CoverLib.dll">
        <Folder>NCover\libs\NCover</Folder>
    </Binary>
    <Binary Include="libs\NCover\Microsoft.VC80.CRT.manifest">
        <Folder>NCover\libs\NCover</Folder>
    </Binary>
    <Binary Include="libs\NCover\MSVCP80.dll">
        <Folder>NCover\libs\NCover</Folder>
    </Binary>
    <Binary Include="libs\NCover\MSVCR80.dll">
        <Folder>NCover\libs\NCover</Folder>
    </Binary>
    <Binary Include="libs\NCover\NCover.Console.exe">
        <Folder>NCover\libs\NCover</Folder>
    </Binary>
    <Binary Include="libs\NCover\NCover.Console.exe.config">
        <Folder>NCover\libs\NCover</Folder>
    </Binary>
    <Binary Include="libs\NCover\NCover.Framework.dll">
        <Folder>NCover\libs\NCover</Folder>
    </Binary>
    <Binary Include="libs\NCover\NCoverFAQ.html">
        <Folder>NCover\libs\NCover</Folder>
    </Binary>
    
    <Binary Include="libs\NCoverExplorer\CommandBars.dll">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer\ConsoleConfig.xsd">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer\ConsoleExample.config">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer\CoverageReport.xsl">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer\ICSharpCode.TextEditor.dll">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer\license.txt">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer\NCoverExplorer.Console.exe">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer\NCoverExplorer.Core.dll">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer\NCoverExplorer.exe">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer\NCoverExplorer.exe.config">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer\NCoverExplorer.NCoverRunner.dll">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer\NCoverExplorerFAQ.html">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
    <Binary Include="libs\NCoverExplorer\NCoverExplorerReleaseNotes.html">
        <Folder>NCover\libs\NCoverExplorer</Folder>
    </Binary>
  </ItemGroup>

  <ItemGroup>
    <Feature Include="FEATURE_NCOVER_INTEGRATION" />

    <TestAssembly Include="Gallio.NCoverIntegration.Tests\bin\Gallio.NCoverIntegration.Tests.dll" />
  </ItemGroup>
</Project>
