<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.MbUnit2Adapter\Gallio.MbUnit2Adapter$(ProjectVariant).csproj" />
    
    <CSharpProject Include="Gallio.MbUnit2Adapter.TestResources\Gallio.MbUnit2Adapter.TestResources$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.MbUnit2Adapter.Tests\Gallio.MbUnit2Adapter.Tests$(ProjectVariant).csproj" />    
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.MbUnit2Adapter\bin\Gallio.MbUnit2Adapter.dll">
        <Folder>MbUnit2</Folder>
    </Binary>
    <PluginFile Include="Gallio.MbUnit2Adapter\Gallio.MbUnit2Adapter.plugin">
        <Folder>MbUnit2</Folder>
    </PluginFile>
    <Binary Include="Gallio.MbUnit2Adapter\Readme.txt">
        <Folder>MbUnit2</Folder>
    </Binary>
    <Binary Include="libs\MbUnit.Framework.dll">
        <Folder>MbUnit2</Folder>
    </Binary>
    <Binary Include="libs\MbUnit.Framework.xml">
        <Folder>MbUnit2</Folder>
    </Binary>
    <Binary Include="libs\MbUnit.Framework.2.0.dll">
        <Folder>MbUnit2</Folder>
    </Binary>
    <Binary Include="libs\MbUnit.Framework.2.0.xml">
        <Folder>MbUnit2</Folder>
    </Binary>
    <Binary Include="libs\QuickGraph.dll">
        <Folder>MbUnit2</Folder>
    </Binary>
    <Binary Include="libs\QuickGraph.xml">
        <Folder>MbUnit2</Folder>
    </Binary>
    <Binary Include="libs\QuickGraph.Algorithms.dll">
        <Folder>MbUnit2</Folder>
    </Binary>
    <Binary Include="libs\QuickGraph.Algorithms.xml">
        <Folder>MbUnit2</Folder>
    </Binary>
    <Binary Include="libs\TestFu.dll">
        <Folder>MbUnit2</Folder>
    </Binary>
    <Binary Include="libs\TestFu.xml">
        <Folder>MbUnit2</Folder>
    </Binary>
    <Binary Include="libs\Refly.dll">
        <Folder>MbUnit2</Folder>
    </Binary>
    <Binary Include="libs\Refly.xml">
        <Folder>MbUnit2</Folder>
    </Binary>
    
    <Binary Include="Gallio.MbUnit2Adapter\Resources\*.ico">
        <Folder>MbUnit2\Resources</Folder>
    </Binary>    
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.MbUnit2Adapter.Tests\bin\Gallio.MbUnit2Adapter.Tests.dll" />
  </ItemGroup>
</Project>
