<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(RootDir)\bin\Module.targets" />

  <ItemGroup>
    <CSharpProject Include="Gallio.AutoCAD\Gallio.AutoCAD$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.AutoCAD.Plugin\Gallio.AutoCAD.Plugin$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.AutoCAD.Tests\Gallio.AutoCAD.Tests$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.AutoCAD.UI\Gallio.AutoCAD.UI$(ProjectVariant).csproj" />
    
    <AssemblyFile Include="Gallio.AutoCAD\bin\Gallio.AutoCAD.dll">
      <ImagePath>bin\AutoCAD</ImagePath>
    </AssemblyFile>
    <PluginFile Include="Gallio.AutoCAD\Gallio.AutoCAD.plugin">
      <ImagePath>bin\AutoCAD</ImagePath>
    </PluginFile>
    <AssemblyFile Include="Gallio.AutoCAD.Plugin\bin\Gallio.AutoCAD.Plugin.dll">
      <ImagePath>bin\AutoCAD</ImagePath>
    </AssemblyFile>
    <AssemblyFile Include="Gallio.AutoCAD.UI\bin\Gallio.AutoCAD.UI.dll">
      <ImagePath>bin\AutoCAD</ImagePath>
    </AssemblyFile>
    <PluginFile Include="Gallio.AutoCAD.UI\Gallio.AutoCAD.UI.plugin">
      <ImagePath>bin\AutoCAD</ImagePath>
    </PluginFile>
    
    <File Include="Gallio.AutoCAD\Resources\Gallio.AutoCAD.ico">
      <ImagePath>bin\AutoCAD\Resources</ImagePath>
    </File>

    <LicenseFile Include="libs\objectarx_license.doc">
      <ImagePath>licenses</ImagePath>
    </LicenseFile>
    
    <TestAssembly Include="Gallio.AutoCAD.Tests\bin\Gallio.AutoCAD.Tests.dll" />

    <Feature Include="FEATURE_AUTOCAD" />
  </ItemGroup>
</Project>
