<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />

  <ItemGroup>
    <CSharpProject Include="Gallio.MSBuildTasks\Gallio.MSBuildTasks$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.MSBuildTasks.Tests\Gallio.MSBuildTasks.Tests$(ProjectVariant).csproj" />

    <PluginFile Include="Gallio.MSBuildTasks\Gallio.MSBuildTasks.plugin">
      <ImagePath>bin</ImagePath>
    </PluginFile>
    <AssemblyFile Include="Gallio.MSBuildTasks\bin\Gallio.MSBuildTasks.dll">
      <ImagePath>bin</ImagePath>
    </AssemblyFile>
    <XmlDocFile Include="Gallio.MSBuildTasks\bin\Gallio.MSBuildTasks.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>

    <TestAssembly Include="Gallio.MSBuildTasks.Tests\bin\Gallio.MSBuildTasks.Tests.dll" />
  </ItemGroup>
</Project>
