<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <CSharpProject Include="Gallio.MSBuildTasks\Gallio.MSBuildTasks.csproj" />
    <CSharpProject Include="Gallio.MSBuildTasks.Tests\Gallio.MSBuildTasks.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.MSBuildTasks\bin\Gallio.MSBuildTasks.dll" />
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.MSBuildTasks.Tests\bin\Gallio.MSBuildTasks.Tests.dll" />
  </ItemGroup>
</Project>
