<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <PropertyGroup>
    <MonoCompatible>false</MonoCompatible>
  </PropertyGroup>
  
  <ItemGroup>
    <CSharpProject Include="Gallio.MSBuildTasks\Gallio.MSBuildTasks$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.MSBuildTasks.Tests\Gallio.MSBuildTasks.Tests$(ProjectVariant).csproj" />

    <PluginFile Include="Gallio.MSBuildTasks\Gallio.MSBuildTasks.plugin" />
    <Binary Include="Gallio.MSBuildTasks\bin\Gallio.MSBuildTasks.dll" />
    <DocumentedAssembly Include="Gallio.MSBuildTasks\bin\Gallio.MSBuildTasks.dll" />

    <TestAssembly Include="Gallio.MSBuildTasks.Tests\bin\Gallio.MSBuildTasks.Tests.dll" />
  </ItemGroup>
</Project>
