<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <PropertyGroup>
    <MonoCompatible>false</MonoCompatible>
  </PropertyGroup>
  
  <ItemGroup>
    <CSharpProject Include="Gallio.TDNetRunner\Gallio.TDNetRunner$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.TDNetRunner.Tests\Gallio.TDNetRunner.Tests$(ProjectVariant).csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.TDNetRunner\bin\Gallio.TDNetRunner.dll">
      <Folder>TDNet</Folder>
    </Binary>
    <PluginFile Include="Gallio.TDNetRunner\Gallio.TDNetRunner.plugin">
      <Folder>TDNet</Folder>
    </PluginFile>
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.TDNetRunner.Tests\bin\Gallio.TDNetRunner.Tests.dll" />
  </ItemGroup>
</Project>
