<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <CSharpProject Include="Gallio.TDNetRunner\Gallio.TDNetRunner.csproj" />
    <CSharpProject Include="Gallio.TDNetRunner.Tests\Gallio.TDNetRunner.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.TDNetRunner\bin\Gallio.TDNetRunner.dll" />
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.TDNetRunner.Tests\bin\Gallio.TDNetRunner.Tests.dll" />
  </ItemGroup>
</Project>
