<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.DLRIntegration\Gallio.DLRIntegration$(ProjectVariant).csproj" />
    
    <CSharpProject Include="Gallio.DLRIntegration.Tests\Gallio.DLRIntegration.Tests$(ProjectVariant).csproj" />    
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.DLRIntegration\bin\Gallio.DLRIntegration.dll">
      <Folder>DLR</Folder>
    </Binary>
    <PluginFile Include="Gallio.DLRIntegration\Gallio.DLRIntegration.plugin">
      <Folder>DLR</Folder>
    </PluginFile>
    <Binary Include="Gallio.DLRIntegration\Gallio.DLRIntegration.dll.config">
      <Folder>DLR</Folder>
    </Binary>

    <TestAssembly Include="Gallio.DLRIntegration.Tests\bin\Gallio.DLRIntegration.Tests.dll" />
	
    <Feature Include="FEATURE_DLR_INTEGRATION" />
  </ItemGroup>

  <Target Name="AfterImage">
    <RemoveDir Directories="$(ImageDir)\bin\DLR\libs" />
    <MakeDir Directories="$(ImageDir)\bin\DLR" />

    <SvnExport RepositoryPath="$(ModuleDir)\libs"
               LocalPath="$(ImageDir)\bin\DLR\libs" />
			   
    <RemoveDir Directories="$(ImageDir)\bin\DLR\Scripts" />
    <MakeDir Directories="$(ImageDir)\bin\DLR" />

    <SvnExport RepositoryPath="$(ModuleDir)\Gallio.DLRIntegration\Scripts"
               LocalPath="$(ImageDir)\bin\DLR\Scripts" />
	       
    <ItemGroup>
      <LibsFiles Include="$(ImageDir)\bin\DLR\libs\**\*" />
      <ScriptsFiles Include="$(ImageDir)\bin\DLR\scripts\**\*" />

      <Token Include="LibsFilesToken">
        <ReplacementValue>@(LibsFiles->'&lt;file path="libs\%(RecursiveDir)%(Filename)%(Extension)"/&gt;', '%0A    ')</ReplacementValue>
      </Token>
      <Token Include="ScriptsFilesToken">
        <ReplacementValue>@(ScriptsFiles->'&lt;file path="scripts\%(RecursiveDir)%(Filename)%(Extension)"/&gt;', '%0A    ')</ReplacementValue>
      </Token>
    </ItemGroup>

    <TemplateFile Template="$(ImageDir)\bin\DLR\Gallio.DLRIntegration.plugin"
		  Tokens="@(Token)" />
    <Delete Files="$(ImageDir)\bin\DLR\Gallio.DLRIntegration.plugin" />
    <Move SourceFiles="$(ImageDir)\bin\DLR\Gallio.DLRIntegration.out"
          DestinationFiles="$(ImageDir)\bin\DLR\Gallio.DLRIntegration.plugin" />
  </Target>

  <Target Name="BeforeDist">
    <Exec Command="&quot;$(ToolsDir)\Wix\heat.exe&quot; dir &quot;$(ImageDir)\bin\DLR\libs&quot; -gg -ke -nologo -sfrag -sreg -t:DLR-libs.xslt -out DLR-libs.wxi" />
    <Exec Command="&quot;$(ToolsDir)\Wix\heat.exe&quot; dir &quot;$(ImageDir)\bin\DLR\Scripts&quot; -gg -ke -nologo -sfrag -sreg -t:DLR-scripts.xslt -out DLR-scripts.wxi" />
  </Target>
</Project>
