<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.DLRIntegration\Gallio.DLRIntegration$(ProjectVariant).csproj" />
    
    <CSharpProject Include="Gallio.DLRIntegration.Tests\Gallio.DLRIntegration.Tests$(ProjectVariant).csproj" />    
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.DLRIntegration\bin\Gallio.DLRIntegration.dll">
      <Folder>DLR</Folder>
    </Binary>
    <PluginFile Include="Gallio.DLRIntegration\Gallio.DLRIntegration.plugin">
      <Folder>DLR</Folder>
    </PluginFile>

    <TestAssembly Include="Gallio.DLRIntegration.Tests\bin\Gallio.DLRIntegration.Tests.dll" />
	
    <Feature Include="FEATURE_DLR_INTEGRATION" />
  </ItemGroup>

  <Target Name="AfterImage">
    <RemoveDir Directories="$(ImageDir)\DLR\libs" />
    <MakeDir Directories="$(ImageDir)\DLR" />

    <SvnExport RepositoryPath="$(ModuleDir)\libs"
               LocalPath="$(ImageDir)\DLR\libs" />
			   
    <RemoveDir Directories="$(ImageDir)\DLR\Scripts" />
    <MakeDir Directories="$(ImageDir)\DLR" />

    <SvnExport RepositoryPath="$(ModuleDir)\Gallio.DLRIntegration\Scripts"
               LocalPath="$(ImageDir)\DLR\Scripts" />
  </Target>

  <Target Name="BeforeDist">
    <Exec Command="&quot;$(ToolsDir)\Wix\heat.exe&quot; dir &quot;$(ImageDir)\DLR\libs&quot; -ag -ke -nologo -sfrag -sreg -t:DLR-libs.xslt -out DLR-libs.wxi" />
    <Exec Command="&quot;$(ToolsDir)\Wix\heat.exe&quot; dir &quot;$(ImageDir)\DLR\Scripts&quot; -ag -ke -nologo -sfrag -sreg -t:DLR-scripts.xslt -out DLR-scripts.wxi" />
  </Target>
</Project>
