//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallio.Icarus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gallio.Icarus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding files.
        /// </summary>
        internal static string AddingFiles {
            get {
                return ResourceManager.GetString("AddingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallio Icarus.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting filter.
        /// </summary>
        internal static string DeletingFilter {
            get {
                return ResourceManager.GetString("DeletingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files....
        /// </summary>
        internal static string Dialogs_CreateAddFilesDialog_Add_Files___ {
            get {
                return ResourceManager.GetString("Dialogs_CreateAddFilesDialog_Add_Files___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project....
        /// </summary>
        internal static string Dialogs_CreateOpenProjectDialog_Open_Project___ {
            get {
                return ResourceManager.GetString("Dialogs_CreateOpenProjectDialog_Open_Project___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project As....
        /// </summary>
        internal static string Dialogs_CreateSaveProjectDialog_Save_Project_As___ {
            get {
                return ResourceManager.GetString("Dialogs_CreateSaveProjectDialog_Save_Project_As___", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Log.
        /// </summary>
        internal static string Execution_Log_Package_Execution_Log {
            get {
                return ResourceManager.GetString("Execution_Log_Package_Execution_Log", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; has been modified..
        /// </summary>
        internal static string FileModified {
            get {
                return ResourceManager.GetString("FileModified", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FilterFailed {
            get {
                object obj = ResourceManager.GetObject("FilterFailed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilterPassed {
            get {
                object obj = ResourceManager.GetObject("FilterPassed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilterSkipped {
            get {
                object obj = ResourceManager.GetObject("FilterSkipped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fixture {
            get {
                object obj = ResourceManager.GetObject("Fixture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon GallioIcarus {
            get {
                object obj = ResourceManager.GetObject("GallioIcarus", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Group {
            get {
                object obj = ResourceManager.GetObject("Group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Main_TaskCanceled_Canceled {
            get {
                return ResourceManager.GetString("Main_TaskCanceled_Canceled", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Namespace {
            get {
                object obj = ResourceManager.GetObject("Namespace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No window with that identifier exists.
        /// </summary>
        internal static string NoWindowWithThatIdentifierExists {
            get {
                return ResourceManager.GetString("NoWindowWithThatIdentifierExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening project.
        /// </summary>
        internal static string OpeningProject {
            get {
                return ResourceManager.GetString("OpeningProject", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap pillar {
            get {
                object obj = ResourceManager.GetObject("pillar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Browser.
        /// </summary>
        internal static string PluginBrowserPackage_AddMenuItem_Plugin_Browser {
            get {
                return ResourceManager.GetString("PluginBrowserPackage_AddMenuItem_Plugin_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &apos;{0}&apos; has been modified..
        /// </summary>
        internal static string ProjectModified {
            get {
                return ResourceManager.GetString("ProjectModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Reload to update the project or Ignore to continue..
        /// </summary>
        internal static string ProjectReloadOrIgnore {
            get {
                return ResourceManager.GetString("ProjectReloadOrIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string ProjectsPackage_AddMenuItem_Properties {
            get {
                return ResourceManager.GetString("ProjectsPackage_AddMenuItem_Properties", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Properties {
            get {
                object obj = ResourceManager.GetObject("Properties", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PropertiesImage {
            get {
                object obj = ResourceManager.GetObject("PropertiesImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Report {
            get {
                object obj = ResourceManager.GetObject("Report", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running tests.
        /// </summary>
        internal static string RunTestsCommand_Running_tests {
            get {
                return ResourceManager.GetString("RunTestsCommand_Running_tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search_Package_AddMenuItem_Search {
            get {
                return ResourceManager.GetString("Search_Package_AddMenuItem_Search", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Test {
            get {
                object obj = ResourceManager.GetObject("Test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asserts.
        /// </summary>
        internal static string TestResultsList_TestResultsList_Asserts {
            get {
                return ResourceManager.GetString("TestResultsList_TestResultsList_Asserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code reference.
        /// </summary>
        internal static string TestResultsList_TestResultsList_Code_reference {
            get {
                return ResourceManager.GetString("TestResultsList_TestResultsList_Code_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (s).
        /// </summary>
        internal static string TestResultsList_TestResultsList_Duration__s_ {
            get {
                return ResourceManager.GetString("TestResultsList_TestResultsList_Duration__s_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string TestResultsList_TestResultsList_File {
            get {
                return ResourceManager.GetString("TestResultsList_TestResultsList_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step name.
        /// </summary>
        internal static string TestResultsList_TestResultsList_Step_name {
            get {
                return ResourceManager.GetString("TestResultsList_TestResultsList_Step_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test kind.
        /// </summary>
        internal static string TestResultsList_TestResultsList_Test_kind {
            get {
                return ResourceManager.GetString("TestResultsList_TestResultsList_Test_kind", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon XmlFile {
            get {
                object obj = ResourceManager.GetObject("XmlFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
