<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <PropertyGroup>
    <LibCheckExe>$(ToolsDir)\LibCheck\LibCheck.exe</LibCheckExe>
    
    <LibCheckTempDir>$(TempDir)\LibCheck</LibCheckTempDir>
    <LibCheckReportDir>$(ReportDir)\LibCheck</LibCheckReportDir>
  </PropertyGroup>

  <ItemGroup>
    <OldVersion Include="3.0.0.285" />
  </ItemGroup>

  <Target Name="AfterTest"
          DependsOnTargets="
	    PrepareLibCheckVersions;
	    PrepareLibCheckTempDir;
	    GenerateLibCheckStoreFiles;
	    GenerateLibCheckReports">
  </Target>

  <Target Name="PrepareLibCheckVersions">
    <ItemGroup>
      <LibCheckVersionDir Include="@(OldVersion->'Versions\%(Identity)')">
        <Version>%(Identity)</Version>
      </LibCheckVersionDir>
      <LibCheckVersionDir Include="$(ImageDir)\bin">
        <Version>$(Version)</Version>
      </LibCheckVersionDir>
    </ItemGroup>
  </Target>

  <Target Name="PrepareLibCheckTempDir">
    <RemoveDir Directories="$(LibCheckTempDir)" />
    <MakeDir Directories="$(LibCheckTempDir)" />

    <ItemGroup>
      <LibCheckRefFile Include="RefFiles\**\*.txt" />
    </ItemGroup>

    <Copy SourceFiles="@(LibCheckRefFile)"
          DestinationFiles="$(LibCheckTempDir)\RefFiles\%(RecursiveDir)%(Filename)%(Extension)" />
  </Target>

  <Target Name="GenerateLibCheckStoreFiles">
    <Message Text="Generating LibCheck store files..."
             Importance="High" />

    <Exec Command="&quot;$(LibCheckExe)&quot; -store Full &quot;%(LibCheckVersionDir.Version)&quot; -full &quot;%(LibCheckVersionDir.FullPath)&quot;"
          WorkingDirectory="$(LibCheckTempDir)" />
  </Target>

  <Target Name="GenerateLibCheckReports">
    <Message Text="Generating LibCheck comparison reports..."
             Importance="High" />

    <MakeDir Directories="$(LibCheckReportDir)" />

    <Exec Command="&quot;$(LibCheckExe)&quot; -compare &quot;%(LibCheckVersionDir.Version)&quot; &quot;$(Version)&quot; -header -bydll -out &quot;$(LibCheckReportDir)\%(LibCheckVersionDir.Version)-to-$(Version)&quot;"
          Condition="'%(LibCheckVersionDir.Version)'!='$(Version)'"
          WorkingDirectory="$(LibCheckTempDir)" />
  </Target>
</Project>
