//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallio.Copy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gallio.Copy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallio Copy.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing source and target plugins.
        /// </summary>
        internal static string ComparePluginsCommand_Comparing_source_and_target_plugins {
            get {
                return ResourceManager.GetString("ComparePluginsCommand_Comparing_source_and_target_plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyForm_Copy {
            get {
                return ResourceManager.GetString("CopyForm_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a target folder..
        /// </summary>
        internal static string CopyForm_Please_select_a_target_folder_ {
            get {
                return ResourceManager.GetString("CopyForm_Please_select_a_target_folder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a source plugin folder.
        /// </summary>
        internal static string CopyForm_Select_a_source_plugin_folder {
            get {
                return ResourceManager.GetString("CopyForm_Select_a_source_plugin_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a target plugin folder.
        /// </summary>
        internal static string CopyForm_Select_a_target_plugin_folder {
            get {
                return ResourceManager.GetString("CopyForm_Select_a_target_plugin_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding plugin path.
        /// </summary>
        internal static string UpdatePluginFolderCommand_Adding_plugin_path {
            get {
                return ResourceManager.GetString("UpdatePluginFolderCommand_Adding_plugin_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying catalog to registry.
        /// </summary>
        internal static string UpdatePluginFolderCommand_Applying_catalog_to_registry {
            get {
                return ResourceManager.GetString("UpdatePluginFolderCommand_Applying_catalog_to_registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populating catalog.
        /// </summary>
        internal static string UpdatePluginFolderCommand_Populating_catalog {
            get {
                return ResourceManager.GetString("UpdatePluginFolderCommand_Populating_catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating list of plugins.
        /// </summary>
        internal static string UpdatePluginFolderCommand_Updating_list_of_plugins {
            get {
                return ResourceManager.GetString("UpdatePluginFolderCommand_Updating_list_of_plugins", resourceCulture);
            }
        }
    }
}
