//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbUnit.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MbUnit.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string BaseStep_RootStepName {
            get {
                return ResourceManager.GetString("BaseStep_RootStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter list already contains a parameter named &apos;{0}&apos;..
        /// </summary>
        internal static string BaseTemplate_ParameterListAlreadyContainsParameterWithSameName {
            get {
                return ResourceManager.GetString("BaseTemplate_ParameterListAlreadyContainsParameterWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of template arguments for template &apos;{0}&apos;, expected {1} but received {2}..
        /// </summary>
        internal static string BaseTemplateBinding_InvalidNumberOfTemplateArguments {
            get {
                return ResourceManager.GetString("BaseTemplateBinding_InvalidNumberOfTemplateArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing argument for template parameter &apos;{0}&apos; of template &apos;{1}&apos;..
        /// </summary>
        internal static string BaseTemplateBinding_MissingArgumentForTemplateParameter {
            get {
                return ResourceManager.GetString("BaseTemplateBinding_MissingArgumentForTemplateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; of .
        /// </summary>
        internal static string CodeReference_ToString_ParameterName {
            get {
                return ResourceManager.GetString("CodeReference_ToString_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MbUnit Gallio v{0}.
        /// </summary>
        internal static string MbUnitFrameworkTemplate_MbUnitGallioFrameworkVersionFormat {
            get {
                return ResourceManager.GetString("MbUnitFrameworkTemplate_MbUnitGallioFrameworkVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while binding value for parameter &apos;{0}&apos;..
        /// </summary>
        internal static string MbUnitTestState_ErrorWhileBindingValueForParameter {
            get {
                return ResourceManager.GetString("MbUnitTestState_ErrorWhileBindingValueForParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template binding does not contain parameter &apos;{0}&apos;..
        /// </summary>
        internal static string MbUnitTestState_TemplateBindingDoesNotContainParameter {
            get {
                return ResourceManager.GetString("MbUnitTestState_TemplateBindingDoesNotContainParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to invoke an instance method of a fixture but the fixture instance is not available..
        /// </summary>
        internal static string MbUnitTestUtils_ExpectedToInvokeAnInstanceMethod {
            get {
                return ResourceManager.GetString("MbUnitTestUtils_ExpectedToInvokeAnInstanceMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a method with signature ({0}) but found ({1})..
        /// </summary>
        internal static string ModelUtils_InvalidSignature {
            get {
                return ResourceManager.GetString("ModelUtils_InvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node to be added is already a child of another node..
        /// </summary>
        internal static string ModelUtils_NodeAlreadyHasAParent {
            get {
                return ResourceManager.GetString("ModelUtils_NodeAlreadyHasAParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string RootTemplate_RootTemplateName {
            get {
                return ResourceManager.GetString("RootTemplate_RootTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string RootTest_RootTestName {
            get {
                return ResourceManager.GetString("RootTest_RootTestName", resourceCulture);
            }
        }
    }
}
