//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbUnit.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MbUnit.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- CANCELED ---.
        /// </summary>
        internal static string ConsoleProgressMonitor_CanceledBanner {
            get {
                return ResourceManager.GetString("ConsoleProgressMonitor_CanceledBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt; CANCELING &lt;&lt;&lt;.
        /// </summary>
        internal static string ConsoleProgressMonitor_CancelingBanner {
            get {
                return ResourceManager.GetString("ConsoleProgressMonitor_CancelingBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Execution Log: Begin Section ({0})].
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_BeginSection_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_BeginSection_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Section Name: {0}.
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_BeginSection_SectionNameFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_BeginSection_SectionNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Execution Log: Close ({0})].
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_Close_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_Close_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Execution Log: End Section ({0})].
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_EndSection_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_EndSection_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Stream Name: {0}.
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_StreamNameFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_StreamNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Text: {0}.
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_TextFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_TextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Attachment Name: {0}.
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_WriteAttachment_AttachmentNameFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_WriteAttachment_AttachmentNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Attachment Content Type: {0}.
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_WriteAttachment_ContentTypeFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_WriteAttachment_ContentTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Execution Log: Write Attachment ({0})].
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_WriteAttachment_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_WriteAttachment_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Execution Log: Write Text ({0})].
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_WriteText_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_WriteText_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Asserts: {0}.
        /// </summary>
        internal static string DebugMonitor_LifecycleEvent_Finish_AssertCountFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_LifecycleEvent_Finish_AssertCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Duration: {0}.
        /// </summary>
        internal static string DebugMonitor_LifecycleEvent_Finish_DurationFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_LifecycleEvent_Finish_DurationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lifecycle: Finish ({0})].
        /// </summary>
        internal static string DebugMonitor_LifecycleEvent_Finish_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_LifecycleEvent_Finish_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Outcome: {0}.
        /// </summary>
        internal static string DebugMonitor_LifecycleEvent_Finish_OutcomeFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_LifecycleEvent_Finish_OutcomeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	State: {0}.
        /// </summary>
        internal static string DebugMonitor_LifecycleEvent_Finish_StateFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_LifecycleEvent_Finish_StateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lifecycle: Enter Phase ({0})].
        /// </summary>
        internal static string DebugMonitor_LifecycleEvent_Phase_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_LifecycleEvent_Phase_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Phase Name: {0}.
        /// </summary>
        internal static string DebugMonitor_LifecycleEvent_Phase_NameFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_LifecycleEvent_Phase_NameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lifecycle: Start ({0})].
        /// </summary>
        internal static string DebugMonitor_LifecycleEvent_Start_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_LifecycleEvent_Start_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Message: {0}] - {1}.
        /// </summary>
        internal static string DebugMonitor_MessageEvent_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_MessageEvent_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}.
        /// </summary>
        internal static string LogMonitor_HeaderFormat {
            get {
                return ResourceManager.GetString("LogMonitor_HeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canceled.
        /// </summary>
        internal static string LogMonitor_Status_Canceled {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string LogMonitor_Status_Error {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        internal static string LogMonitor_Status_Failed {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ignored.
        /// </summary>
        internal static string LogMonitor_Status_Ignored {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inconclusive.
        /// </summary>
        internal static string LogMonitor_Status_Inconclusive {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Inconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not run.
        /// </summary>
        internal static string LogMonitor_Status_NotRun {
            get {
                return ResourceManager.GetString("LogMonitor_Status_NotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passed.
        /// </summary>
        internal static string LogMonitor_Status_Passed {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skipped.
        /// </summary>
        internal static string LogMonitor_Status_Skipped {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting.
        /// </summary>
        internal static string LogMonitor_Status_Starting {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string LogMonitor_Status_Unknown {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Unknown", resourceCulture);
            }
        }
    }
}
