<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  <Import Project="MSTest.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.MSTestAdapter\Gallio.MSTestAdapter.csproj" />
    <CSharpProject Include="Gallio.MSTestAdapter.TestResources\Gallio.MSTestAdapter.TestResources.csproj" />
    <CSharpProject Include="Gallio.MSTestAdapter.Tests\Gallio.MSTestAdapter.Tests.csproj" />

    <CSharpProject Include="Gallio.MSTestRunner\Gallio.MSTestRunner.csproj" />
    <CSharpProject Include="Gallio.MSTestRunner.Tests\Gallio.MSTestRunner.Tests.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$(MSTestFrameworkInstalled)">
    <Binary Include="Gallio.MSTestAdapter\bin\Gallio.MSTestAdapter.dll">
      <Folder>MSTest</Folder>
    </Binary>
    <Binary Include="Gallio.MSTestAdapter\Gallio.MSTestAdapter.plugin">
      <Folder>MSTest</Folder>
    </Binary>
    <Binary Include="Gallio.MSTestAdapter\Readme.txt">
      <Folder>MSTest</Folder>
    </Binary>

    <TestAssembly Include="Gallio.MSTestAdapter.Tests\bin\Gallio.MSTestAdapter.Tests.dll" />

    <Feature Include="FEATURE_MSTEST_ADAPTER" />
  </ItemGroup>

  <ItemGroup Condition="$(MSTestVSIPInstalled)">
    <Binary Include="Gallio.MSTestRunner\bin\Gallio.MSTestRunner.dll">
      <Folder>MSTest</Folder>
    </Binary>
    <Binary Include="Gallio.MSTestRunner\bin\Gallio.MSTestRunner.dll.config">
      <Folder>MSTest</Folder>
    </Binary>

    <TestAssembly Include="Gallio.MSTestRunner.Tests\bin\Gallio.MSTestRunner.Tests.dll" />

    <Feature Include="FEATURE_MSTEST_RUNNER" />
  </ItemGroup>
</Project>
