<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(RootDir)\bin\Module.targets" />

  <PropertyGroup>
    <ReportResourcesDir>$(SourceDir)\Gallio\Gallio.Reports\Resources</ReportResourcesDir>
  </PropertyGroup>
    
  <ItemGroup>
    <CSharpProject Include="CCNet.Gallio.WebDashboard.Plugin\CCNet.Gallio.WebDashboard.Plugin$(ProjectVariant).csproj" />
    
    <File Include="docs\How to use Gallio with CruiseControl.Net.txt">
      <ImagePath>extras\CCNet</ImagePath>
    </File>
    
    <PdbFile Include="CCNet.Gallio.WebDashboard.Plugin\bin\CCNet.Gallio.WebDashboard.Plugin.pdb">
      <ExcludeFromImage>true</ExcludeFromImage>
    </PdbFile>
    <CCNetPackageFile Include="CCNet.Gallio.WebDashboard.Plugin\bin\CCNet.Gallio.WebDashboard.Plugin.dll">
      <Folder>bin</Folder>
    </CCNetPackageFile>
    <CCNetPackageFile Include="$(ReportResourcesDir)\css\*"
                      Exclude="$(ReportResourcesDir)\css\Gallio-Report.Generated.css">
      <Folder>gallio\css</Folder>
    </CCNetPackageFile>
    <CCNetPackageFile Include="$(ReportResourcesDir)\js\*">
      <Folder>gallio\js</Folder>
    </CCNetPackageFile>
    <CCNetPackageFile Include="$(ReportResourcesDir)\img\*">
      <Folder>gallio\img</Folder>
    </CCNetPackageFile>
    <CCNetPackageFile Include="$(ReportResourcesDir)\xsl\Gallio-Report.ccnet-details.xsl">
      <Folder>gallio\xsl</Folder>
    </CCNetPackageFile>
    <CCNetPackageFile Include="$(ReportResourcesDir)\xsl\Gallio-Report.ccnet-details-condensed.xsl">
      <Folder>gallio\xsl</Folder>
    </CCNetPackageFile>
    <CCNetPackageFile Include="$(ReportResourcesDir)\xsl\Gallio-Report.html+xhtml.xsl">
      <Folder>gallio\xsl</Folder>
    </CCNetPackageFile>
    <CCNetPackageFile Include="$(ReportResourcesDir)\xsl\Gallio-Report.common.xsl">
      <Folder>gallio\xsl</Folder>
    </CCNetPackageFile>
  </ItemGroup>

  <Target Name="AfterImage">
    <Message Text="Generating CCNet package..."
             Importance="High" />
    
    <Delete Files="$(ModuleImageDir)\extras\CCNet\GallioReports.zip"
            Condition="Exists('$(ModuleImageDir)\extras\CCNet\GallioReports.zip')" />

    <RemoveDir Directories="$(ModuleTempDir)\CCNet\GallioReports" />
    <MakeDir Directories="$(ModuleTempDir)\CCNet\GallioReports;$(ModuleImageDir)\extras\CCNet" />

    <Copy SourceFiles="@(CCNetPackageFile)"
          DestinationFiles="@(CCNetPackageFile->'$(ModuleTempDir)\CCNet\GallioReports\%(ImagePath)\%(Filename)%(Extension)')" />

    <ItemGroup>
      <CCNetPackageFileTempCopy Include="$(ModuleTempDir)\CCNet\GallioReports\**\*" />
    </ItemGroup>

    <Zip Files="@(CCNetPackageFileTempCopy)"
         WorkingDirectory="$(ModuleTempDir)\CCNet\GallioReports"
         ZipFileName="$(ModuleImageDir)\extras\CCNet\GallioReports.zip"
         ZipLevel="9"
         Comment="This archive contains MbUnit Samples.  Extract them to a directory of your choice to run them." />
  </Target>
</Project>
