<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.Echo\Gallio.Echo$(ProjectVariant).csproj" />
    
    <CSharpProject Include="Gallio.Echo.Tests\Gallio.Echo.Tests$(ProjectVariant).csproj" />    
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.Echo\bin\Gallio.Echo.exe" />
    <Binary Include="Gallio.Echo\bin\Gallio.Echo.exe.config" />
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.Echo.Tests\bin\Gallio.Echo.Tests.dll" />
  </ItemGroup>
</Project>
