//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallio.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gallio.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string CommandLineArgumentAttributeTests_Description {
            get {
                return ResourceManager.GetString("CommandLineArgumentAttributeTests_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long name.
        /// </summary>
        internal static string CommandLineArgumentAttributeTests_LongName {
            get {
                return ResourceManager.GetString("CommandLineArgumentAttributeTests_LongName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon CommandLineArgumentAttributeTests_NotAStringResource {
            get {
                object obj = ResourceManager.GetObject("CommandLineArgumentAttributeTests_NotAStringResource", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string CommandLineArgumentAttributeTests_ShortName {
            get {
                return ResourceManager.GetString("CommandLineArgumentAttributeTests_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonym1.
        /// </summary>
        internal static string CommandLineArgumentAttributeTests_Synonym1 {
            get {
                return ResourceManager.GetString("CommandLineArgumentAttributeTests_Synonym1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonym2.
        /// </summary>
        internal static string CommandLineArgumentAttributeTests_Synonym2 {
            get {
                return ResourceManager.GetString("CommandLineArgumentAttributeTests_Synonym2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value label.
        /// </summary>
        internal static string CommandLineArgumentAttributeTests_ValueLabel {
            get {
                return ResourceManager.GetString("CommandLineArgumentAttributeTests_ValueLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MbUnitLogo {
            get {
                object obj = ResourceManager.GetObject("MbUnitLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
