<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(RootDir)\Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.Reports\Gallio.Reports.csproj" />
    <CSharpProject Include="Gallio.Reports.Tests\Gallio.Reports.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.Reports\bin\Gallio.Reports.dll">
        <Folder>Reports</Folder>
    </Binary>
    <Binary Include="Gallio.Reports\Gallio.Reports.plugin">
        <Folder>Reports</Folder>
    </Binary>
    <Binary Include="Gallio.Reports\Readme.txt">
        <Folder>Reports</Folder>
    </Binary>
    <Binary Include="Gallio.Reports\css\*">
        <Folder>Reports\css</Folder>
    </Binary>
    <Binary Include="Gallio.Reports\js\*">
        <Folder>Reports\js</Folder>
    </Binary>
    <Binary Include="Gallio.Reports\img\*">
        <Folder>Reports\img</Folder>
    </Binary>
    <Binary Include="Gallio.Reports\xsl\*">
        <Folder>Reports\xsl</Folder>
    </Binary>
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.Reports.Tests\bin\Gallio.Reports.Tests.dll" />
  </ItemGroup>
</Project>
