//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbUnit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MbUnit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Database xmlns=&quot;Gallio.Framework.Data.Generation&quot;&gt;
        ///  &lt;!-- Reference: Countries or areas, codes and abbreviations (04/15/2009)
        ///  [http://unstats.un.org/unsd/methods/m49/m49alpha.htm] --&gt;
        ///  &lt;Item&gt;James&lt;/Item&gt;
        ///  &lt;Item&gt;Afghanistan&lt;/Item&gt;
        ///  &lt;Item&gt;Åland Island&lt;/Item&gt;
        ///  &lt;Item&gt;Albania&lt;/Item&gt;
        ///  &lt;Item&gt;Algeria&lt;/Item&gt;
        ///  &lt;Item&gt;American Samoa&lt;/Item&gt;
        ///  &lt;Item&gt;Andorra&lt;/Item&gt;
        ///  &lt;Item&gt;Angola&lt;/Item&gt;
        ///  &lt;Item&gt;Anguilla&lt;/Item&gt;
        ///  &lt;Item&gt;Antigua and Barbuda&lt;/Item&gt;
        ///  &lt;Item&gt;Argentin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Database_EnCountries {
            get {
                return ResourceManager.GetString("Database_EnCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Database xmlns=&quot;Gallio.Framework.Data.Generation&quot;&gt;
        ///  &lt;Item&gt;James&lt;/Item&gt;
        ///  &lt;Item&gt;John&lt;/Item&gt;
        ///  &lt;Item&gt;Robert&lt;/Item&gt;
        ///  &lt;Item&gt;Michael&lt;/Item&gt;
        ///  &lt;Item&gt;William&lt;/Item&gt;
        ///  &lt;Item&gt;David&lt;/Item&gt;
        ///  &lt;Item&gt;Richard&lt;/Item&gt;
        ///  &lt;Item&gt;Charles&lt;/Item&gt;
        ///  &lt;Item&gt;Joseph&lt;/Item&gt;
        ///  &lt;Item&gt;Thomas&lt;/Item&gt;
        ///  &lt;Item&gt;Christopher&lt;/Item&gt;
        ///  &lt;Item&gt;Daniel&lt;/Item&gt;
        ///  &lt;Item&gt;Paul&lt;/Item&gt;
        ///  &lt;Item&gt;Mark&lt;/Item&gt;
        ///  &lt;Item&gt;Donald&lt;/Item&gt;
        ///  &lt;Item&gt;George&lt;/Item&gt;
        ///  &lt;Item&gt;Kenneth&lt;/Item&gt;
        ///  &lt;Item&gt;Steven&lt;/Item&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Database_EnUSMaleNames {
            get {
                return ResourceManager.GetString("Database_EnUSMaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema 
        ///  elementFormDefault=&quot;qualified&quot; 
        ///  targetNamespace=&quot;Gallio.Framework.Data.Generation&quot; 
        ///  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;Database&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;unbounded&quot; name=&quot;Item&quot; type=&quot;xs:string&quot; /&gt;
        ///      &lt;/xs:sequence&gt;
        ///    &lt;/xs:complexType&gt;
        ///  &lt;/xs:element&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        internal static string Database_Schema {
            get {
                return ResourceManager.GetString("Database_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MbUnit v{0}.
        /// </summary>
        internal static string MbUnitFrameworkTest_MbUnitFrameworkVersionFormat {
            get {
                return ResourceManager.GetString("MbUnitFrameworkTest_MbUnitFrameworkVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MbUnit v3.
        /// </summary>
        internal static string MbUnitTestFramework_FrameworkName {
            get {
                return ResourceManager.GetString("MbUnitTestFramework_FrameworkName", resourceCulture);
            }
        }
    }
}
