<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <CSharpProject Include="Gallio\Gallio.csproj" />
    <CSharpProject Include="Gallio35\Gallio35.csproj" />
    <CSharpProject Include="Gallio.Host\Gallio.Host.csproj" />
    <CSharpProject Include="Gallio.Tests\Gallio.Tests.csproj" />
    <CSharpProject Include="Gallio.Loader\Gallio.Loader.csproj" />
    <CSharpProject Include="Gallio.Reports\Gallio.Reports.csproj" />
    <CSharpProject Include="Gallio.Reports.Tests\Gallio.Reports.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <DocumentedAssembly Include="Gallio\bin\Gallio.dll" />
    <DocumentedAssembly Include="Gallio35\bin\Gallio35.dll" />
    <DocumentedAssembly Include="Gallio.Loader\bin\Gallio.Loader.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Gallio Website.url" />
  
    <Binary Include="Gallio\bin\Gallio.XmlSerializers.dll" />
    <Binary Include="Gallio\Gallio.plugin" />

    <Binary Include="Gallio.Host\bin\Gallio.Host.exe" />
    <Binary Include="Gallio.Host\Gallio.Host.exe.config" />

    <Binary Include="Gallio.Loader\bin\Gallio.Loader.dll" />
    <Binary Include="Gallio.Loader\bin\Gallio.Loader.pdb" />
    
    <Binary Include="Gallio35\bin\Gallio35.dll" />
    <Binary Include="Gallio35\bin\Gallio35.pdb" />
    <Binary Include="Gallio35\Gallio35.plugin" />
    
    <Binary Include="Gallio.Reports\bin\Gallio.Reports.dll">
        <Folder>Reports</Folder>
    </Binary>
    <Binary Include="Gallio.Reports\Gallio.Reports.plugin">
        <Folder>Reports</Folder>
    </Binary>
    <Binary Include="Gallio.Reports\Readme.txt">
        <Folder>Reports</Folder>
    </Binary>
    <Binary Include="Gallio.Reports\css\*">
        <Folder>Reports\css</Folder>
    </Binary>
    <Binary Include="Gallio.Reports\js\*">
        <Folder>Reports\js</Folder>
    </Binary>
    <Binary Include="Gallio.Reports\img\*">
        <Folder>Reports\img</Folder>
    </Binary>
    <Binary Include="Gallio.Reports\xsl\*">
        <Folder>Reports\xsl</Folder>
    </Binary>
  </ItemGroup>

  <ItemGroup>
    <Document Include="Docs\*.txt" />
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.Tests\bin\Gallio.Tests.dll" />
    <TestAssembly Include="Gallio.Reports.Tests\bin\Gallio.Reports.Tests.dll" />
  </ItemGroup>

  <Target Name="AfterImage">
    <Message Text="Running ILMerge on Gallio.dll..."
             Importance="High" />

    <Exec Command="&quot;$(ToolsDir)\ILMerge\ILMerge.exe&quot; &quot;Gallio\bin\Gallio.dll&quot; &quot;Gallio\bin\Castle.Core.dll&quot; &quot;Gallio\bin\Castle.MicroKernel.dll&quot; &quot;Gallio\bin\Castle.Windsor.dll&quot; &quot;Gallio\bin\Castle.DynamicProxy2.dll&quot; &quot;Gallio\bin\Mono.Cecil.dll&quot; /internalize &quot;/out:$(ImageDir)\bin\Gallio.dll&quot; &quot;/keyfile:$(SourceDir)\Key.snk&quot;" />
  </Target>
</Project>
