<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <CSharpProject Include="Gallio\Gallio.csproj" />
    <CSharpProject Include="Gallio.Host\Gallio.Host.csproj" />
    <CSharpProject Include="Gallio.Tests\Gallio.Tests.csproj" />

    <CSharpProject Include="Plugins\Gallio.Plugin.Reports\Gallio.Plugin.Reports.csproj" />
    <CSharpProject Include="Plugins\Gallio.Plugin.Reports.Tests\Gallio.Plugin.Reports.Tests.csproj" />

    <CSharpProject Include="Runners\Gallio.Echo\Gallio.Echo.csproj" />
    <CSharpProject Include="Runners\Gallio.Echo.Tests\Gallio.Echo.Tests.csproj" />

    <CSharpProject Include="Runners\Gallio.Icarus\Gallio.Icarus.csproj" />
    <CSharpProject Include="Runners\Gallio.Icarus.Tests\Gallio.Icarus.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="$(LibsDir)\Castle\bin\Castle.Core.dll" />
    <Binary Include="$(LibsDir)\Castle\bin\Castle.MicroKernel.dll" />
    <Binary Include="$(LibsDir)\Castle\bin\Castle.Windsor.dll" />
    <Binary Include="$(LibsDir)\Castle\bin\Castle.DynamicProxy2.dll" />

    <Binary Include="$(LibsDir)\Components\ZedGraph.dll" />
    <Binary Include="$(LibsDir)\Components\ICSharpCode.TextEditor.dll" />
    <Binary Include="$(LibsDir)\ReferenceAssemblies\System.Core.dll" />
    <Binary Include="$(LibsDir)\ReferenceAssemblies\System.Management.Automation.dll" />

    <Binary Include="Gallio\bin\Gallio.dll" />
    <Binary Include="Gallio\bin\Gallio.XmlSerializers.dll" />
    <Binary Include="Gallio\Gallio.plugin" />

    <Binary Include="Gallio.Host\bin\Gallio.Host.exe" />

    <Binary Include="Plugins\Gallio.Plugin.Reports\bin\Gallio.Plugin.Reports.dll">
        <Folder>Reports</Folder>
    </Binary>
    <Binary Include="Plugins\Gallio.Plugin.Reports\Gallio.Plugin.Reports.plugin">
        <Folder>Reports</Folder>
    </Binary>
    <Binary Include="Plugins\Gallio.Plugin.Reports\Readme.txt">
        <Folder>Reports</Folder>
    </Binary>
    <Binary Include="Plugins\Gallio.Plugin.Reports\css\*">
        <Folder>Reports\css</Folder>
    </Binary>
    <Binary Include="Plugins\Gallio.Plugin.Reports\js\*">
        <Folder>Reports\js</Folder>
    </Binary>
    <Binary Include="Plugins\Gallio.Plugin.Reports\img\*">
        <Folder>Reports\img</Folder>
    </Binary>
    <Binary Include="Plugins\Gallio.Plugin.Reports\xsl\*">
        <Folder>Reports\xsl</Folder>
    </Binary>

    <Binary Include="Runners\Gallio.Echo\bin\Gallio.Echo.exe" />
    <Binary Include="Runners\Gallio.Echo\bin\Gallio.Echo.exe.config" />

    <Binary Include="Runners\Gallio.Icarus\bin\Gallio.Icarus.exe" />
    <Binary Include="Runners\Gallio.Icarus\bin\Gallio.Icarus.exe.config" />    
  </ItemGroup>

  <ItemGroup>
    <Document Include="Docs\*.txt" />
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.Tests\bin\Gallio.Tests.dll" />

    <TestAssembly Include="Plugins\Gallio.Plugin.Reports.Tests\bin\Gallio.Plugin.Reports.Tests.dll" />

    <TestAssembly Include="Runners\Gallio.Echo.Tests\bin\Gallio.Echo.Tests.dll" />
    <TestAssembly Include="Runners\Gallio.Icarus.Tests\bin\Gallio.Icarus.Tests.dll" />
  </ItemGroup>
</Project>
