<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(RootDir)\Module.targets" />

  <ItemGroup>
    <CSharpProject Include="Gallio\Gallio.csproj" />
    <CSharpProject Include="Gallio.Host\Gallio.Host.csproj" />
    <CSharpProject Include="Gallio.Tests\Gallio.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <DocumentedAssembly Include="Gallio\bin\Gallio.dll" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="$(RootDir)\libs\Castle\bin\Castle.Core.dll" />
    <Binary Include="$(RootDir)\libs\Castle\bin\Castle.MicroKernel.dll" />
    <Binary Include="$(RootDir)\libs\Castle\bin\Castle.Windsor.dll" />
    <Binary Include="$(RootDir)\libs\Castle\bin\Castle.DynamicProxy2.dll" />

    <Binary Include="$(RootDir)\libs\ReferenceAssemblies\System.Core.dll" />

    <Binary Include="Gallio\bin\Gallio.dll" />
    <Binary Include="Gallio\bin\Gallio.pdb" />
    <Binary Include="Gallio\bin\Gallio.XmlSerializers.dll" />
    <Binary Include="Gallio\Gallio.plugin" />

    <Binary Include="Gallio.Host\bin\Gallio.Host.exe" />
  </ItemGroup>

  <ItemGroup>
    <Document Include="Docs\*.txt" />
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.Tests\bin\Gallio.Tests.dll" />
  </ItemGroup>
</Project>
