//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbUnit.Plugin.MbUnit2Adapter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MbUnit.Plugin.MbUnit2Adapter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test controller has been disposed..
        /// </summary>
        internal static string MbUnit2TestController_ControlledWasDisposedException {
            get {
                return ResourceManager.GetString("MbUnit2TestController_ControlledWasDisposedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of inner exception stack trace.
        /// </summary>
        internal static string MbUnit2TestController_EndOfInnerExceptionStackTrace {
            get {
                return ResourceManager.GetString("MbUnit2TestController_EndOfInnerExceptionStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing MbUnit v2 test runner..
        /// </summary>
        internal static string MbUnit2TestController_InitializingMbUnitTestRunner {
            get {
                return ResourceManager.GetString("MbUnit2TestController_InitializingMbUnitTestRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running MbUnit v2 tests..
        /// </summary>
        internal static string MbUnit2TestController_RunningMbUnitTests {
            get {
                return ResourceManager.GetString("MbUnit2TestController_RunningMbUnitTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run assembly set up: {0}..
        /// </summary>
        internal static string MbUnit2TestController_StatusMessage_RunningAssemblySetUp {
            get {
                return ResourceManager.GetString("MbUnit2TestController_StatusMessage_RunningAssemblySetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run assembly tear down: {0}..
        /// </summary>
        internal static string MbUnit2TestController_StatusMessage_RunningAssemblyTearDown {
            get {
                return ResourceManager.GetString("MbUnit2TestController_StatusMessage_RunningAssemblyTearDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run fixture set up: {0}..
        /// </summary>
        internal static string MbUnit2TestController_StatusMessage_RunningFixtureSetUp {
            get {
                return ResourceManager.GetString("MbUnit2TestController_StatusMessage_RunningFixtureSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run fixture tear down: {0}..
        /// </summary>
        internal static string MbUnit2TestController_StatusMessage_RunningFixtureTearDown {
            get {
                return ResourceManager.GetString("MbUnit2TestController_StatusMessage_RunningFixtureTearDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run test: {0}..
        /// </summary>
        internal static string MbUnit2TestController_StatusMessage_RunningTest {
            get {
                return ResourceManager.GetString("MbUnit2TestController_StatusMessage_RunningTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MbUnit v2.
        /// </summary>
        internal static string MbUnit2TestFramework_FrameworkName {
            get {
                return ResourceManager.GetString("MbUnit2TestFramework_FrameworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MbUnit v{0}.
        /// </summary>
        internal static string MbUnit2TestFramework_FrameworkTemplateName {
            get {
                return ResourceManager.GetString("MbUnit2TestFramework_FrameworkTemplateName", resourceCulture);
            }
        }
    }
}
