<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <ItemGroup>
    <CSharpProject Include="Unit Testing\MbUnit.Samples\MbUnit.Samples$(ProjectVariant).csproj" />

    <CSharpProject Include="Web Testing with WatiN\MbUnit.Samples.WebTestingWithWatiN\MbUnit.Samples.WebTestingWithWatiN$(ProjectVariant).csproj" />

    <CSharpProject Include="GUI Testing with White\MbUnit.Samples.GUITestingWithWhite\MbUnit.Samples.GUITestingWithWhite$(ProjectVariant).csproj" />

    <File Include="Readme.txt">
      <ImagePath>samples\MbUnit</ImagePath>
    </File>

    <ExportArchive Include="Unit Testing">
      <ImagePath>samples\MbUnit\Unit Testing.zip</ImagePath>
    </ExportArchive>
    
    <ExportArchive Include="Web Testing with WatiN">
      <ImagePath>samples\MbUnit\Web Testing with WatiN.zip</ImagePath>
    </ExportArchive>
    
    <ExportArchive Include="GUI Testing with White">
      <ImagePath>samples\MbUnit\GUI Testing with White.zip</ImagePath>
    </ExportArchive>
  </ItemGroup>
</Project>
