<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <ItemGroup>
    <ModuleReference Include="..\MbUnit.module" />

    <CSharpProject Include="MbUnit.Samples\MbUnit.Samples.csproj" />
    <CSharpProject Include="MbUnit.Samples.VSTSIntegration\MbUnit.Samples.VSTSIntegration.csproj" />

    <ExcludedFile Include="*.module" />
    <ExcludedFile Include="*.wxs" />
  </ItemGroup>

  <Target Name="AfterImage">
    <RemoveDir Directories="$(ImageDir)\samples\MbUnit" />
    <MakeDir Directories="$(ImageDir)\samples" />
    
    <SvnExport RepositoryPath="$(ModuleDir)"
               LocalPath="$(ImageDir)\samples\MbUnit" />

    <Delete Files="@(ExcludedFile->'$(ImageDir)\samples\MbUnit\%(Identity)')"
            Condition="'@(ExcludedFile)'!=''" />
  </Target>
</Project>
