<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <ItemGroup>
    <CSharpProject Include="MbUnit.Samples\MbUnit.Samples.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Extra Include="*.sln">
        <Folder>Samples</Folder>
    </Extra>
    <Extra Include="*.vsmdi">
        <Folder>Samples</Folder>
    </Extra>
    <Extra Include="*.testrunconfig">
        <Folder>Samples</Folder>
    </Extra>
    <Extra Include="**\*.cs" Exclude="**\AdditionalAssemblyInfo.cs">
        <Folder>Samples</Folder>
    </Extra>
    <Extra Include="**\*.resx">
        <Folder>Samples</Folder>
    </Extra>
    <Extra Include="**\*.png">
        <Folder>Samples</Folder>
    </Extra>
    <Extra Include="**\*.csproj">
        <Folder>Samples</Folder>
    </Extra>
  </ItemGroup>
</Project>
