<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.Icarus\Gallio.Icarus$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.Icarus.Tests\Gallio.Icarus.Tests$(ProjectVariant).csproj" />
    
    <AssemblyFile Include="Gallio.Icarus\bin\Gallio.Icarus.exe">
      <ImagePath>bin</ImagePath>
    </AssemblyFile>
    <ConfigFile Include="Gallio.Icarus\bin\Gallio.Icarus.exe.config">
      <ImagePath>bin</ImagePath>
    </ConfigFile>
    <PluginFile Include="Gallio.Icarus\Gallio.Icarus.plugin">
      <ImagePath>bin</ImagePath>
    </PluginFile>
    <AssemblyFile Include="Gallio.Icarus\bin\Gallio.Icarus.XmlSerializers.dll">
      <ImagePath>bin</ImagePath>
    </AssemblyFile>
    <File Include="Gallio.Icarus\Resources\Gallio.Icarus.ico">
      <ImagePath>bin\Resources</ImagePath>
    </File>

    <AssemblyFile Include="libs\ICSharpCode.TextEditor.dll">
      <ImagePath>bin</ImagePath>
    </AssemblyFile>
    
    <TestAssembly Include="Gallio.Icarus.Tests\bin\Gallio.Icarus.Tests.dll" />
  </ItemGroup>
</Project>
