<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.Icarus\Gallio.Icarus$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.Icarus.Tests\Gallio.Icarus.Tests$(ProjectVariant).csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.Icarus\bin\Gallio.Icarus.exe" />
    <PluginFile Include="Gallio.Icarus\bin\Gallio.Icarus.exe.config" />    
    <Binary Include="Gallio.Icarus\bin\Gallio.Icarus.XmlSerializers.dll" />

    <Binary Include="libs\Aga.Controls.dll" />
    <Binary Include="libs\ICSharpCode.TextEditor.dll" />
    <Binary Include="libs\WeifenLuo.WinFormsUI.Docking.dll" />
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.Icarus.Tests\bin\Gallio.Icarus.Tests.dll" />
  </ItemGroup>
</Project>
