<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(RootDir)\bin\Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.Copy\Gallio.Copy$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.Copy.Tests\Gallio.Copy.Tests$(ProjectVariant).csproj" />
    
    <PluginFile Include="Gallio.Copy\Gallio.Copy.plugin">
      <ImagePath>bin</ImagePath>
    </PluginFile>
    <AssemblyFile Include="Gallio.Copy\bin\Gallio.Copy.exe">
      <ImagePath>bin</ImagePath>
    </AssemblyFile>
    <PdbFile Include="Gallio.Copy\bin\Gallio.Copy.pdb">
      <ExcludeFromImage>true</ExcludeFromImage>
    </PdbFile>
    <ConfigFile Include="Gallio.Copy\bin\Gallio.Copy.exe.config">
      <ImagePath>bin</ImagePath>
    </ConfigFile>
    <File Include="Gallio.Copy\Resources\Gallio.Copy.ico">
      <ImagePath>bin\Resources</ImagePath>
    </File>
    
    <TestAssembly Include="Gallio.Copy.Tests\bin\Gallio.Copy.Tests.dll" />

    <!-- Not ready for prime time yet.     
    <Feature Include="FEATURE_COPY" />
    -->
  </ItemGroup>
</Project>
