@echo off
REM Applies license boilerplate to all code files.

setlocal
set BOILERPLATE_DIR=%~dp0

echo Adding missing license boilerplate...
call :APPLY_BOILERPLATE "*.cs" "%BOILERPLATE_DIR%\CSLicenseBoilerplate.txt"

echo.
exit /b 0


:APPLY_BOILERPLATE
set PATTERN=%~1
set LICENSE_FILE=%~2

for /R "." %%V in (%PATTERN%) do (
  if /I not "%%~nV"=="AdditionalAssemblyInfo" (
    findstr /R /C:"Copyright .* Gallio Project - http://www\.gallio\.org/" /C:"<auto-generated>" "%%V" >nul
    if errorlevel 1 (
      echo - %%V
      call :PREFIX_WITH_LICENSE_FILE "%%V"
    )
  )
)
goto :EOF


:PREFIX_WITH_LICENSE_FILE
REM Use sed to strip out UTF8 byte order marks before adding the boilerplate.
type "%LICENSE_FILE%" "%~1" 2>nul | sed -e "s/\xEF\xBB\xBF//" > "%~1.new"
if errorlevel 1 (
  echo     Error applying boilerplate!
) else (
  move /Y "%~1.new" "%~1" >nul
  if errorlevel 1 (
    echo     Error replacing source file!
  )
)
exit /b 0

