<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />

  <ItemGroup>
    <Module Include="Common\Common.module">
      <Inherit>true</Inherit>
    </Module>
    
    <Module Include="Gallio\Gallio.module">
      <Inherit>true</Inherit>
    </Module>
    
    <Module Include="MbUnit\MbUnit.module">
      <Inherit>true</Inherit>
    </Module>
    
    <Module Include="Extensions\Ambience\Ambience.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\AutoCAD\AutoCAD.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\CCNet\CCNet.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\ControlPanel\ControlPanel.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\CSUnit\CSUnit.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\DLR\DLR.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\Echo\Echo.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\Icarus\Icarus.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\MbUnit2\MbUnit2.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\MSBuild\MSBuild.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\MSTest\MSTest.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\NAnt\NAnt.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\Navigator\Navigator.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\NCover\NCover.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\NUnit\NUnit248.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\NUnit\NUnit25.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\PowerShell\PowerShell.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\ReSharper\ReSharper31.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\ReSharper\ReSharper40.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\ReSharper\ReSharper41.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\ReSharper\ReSharper45.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\ReSharper\ReSharper50.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\RSpec\RSpec.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\TDNet\TDNet.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\TeamCity\TeamCity.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\TypeMock\TypeMock.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\Utility\Utility.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\VisualStudio\VisualStudio.Interop.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\VisualStudio\VisualStudio90.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\VisualStudio\VisualStudio100.module">
      <Inherit>true</Inherit>
    </Module>
    <Module Include="Extensions\Xunit\Xunit.module">
      <Inherit>true</Inherit>
    </Module>
  </ItemGroup>
</Project>
