<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />

  <ItemGroup>
    <Module Include="Common\Common.module" />
    <Module Include="Gallio\Gallio.module" />
    <Module Include="MbUnit\MbUnit.module" />
    
    <Module Include="Extensions\Copy\Copy.module">
      <Inherit>true</Inherit>
    </Module>
  </ItemGroup>
</Project>
