<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />
  <Import Project="VisualStudio100.targets" />
  
  <ItemGroup Condition="'$(DotNetFrameworkVersion)'=='4.0' and $(VSIP100Installed)">
    <CSharpProject Include="Gallio.VisualStudio.Shell\Gallio.VisualStudio.Shell100$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.VisualStudio.Shell.Tests\Gallio.VisualStudio.Shell100.Tests$(ProjectVariant).csproj" />
    
    <CSharpProject Include="Gallio.VisualStudio.Sail\Gallio.VisualStudio.Sail100$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.VisualStudio.Sail.Tests\Gallio.VisualStudio.Sail100.Tests$(ProjectVariant).csproj" />
  
    <CSharpProject Include="Gallio.VisualStudio.Tip\Gallio.VisualStudio.Tip100$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.VisualStudio.Tip.Proxy\Gallio.VisualStudio.Tip100.Proxy$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.VisualStudio.Tip.Tests\Gallio.VisualStudio.Tip100.Tests$(ProjectVariant).csproj" />

    <AssemblyFile Include="Gallio.VisualStudio.Shell\bin\v10.0\Gallio.VisualStudio.Shell100.dll">
      <ImagePath>bin\VisualStudio\v10.0</ImagePath>
    </AssemblyFile>
    <PluginFile Include="Gallio.VisualStudio.Shell\Gallio.VisualStudio.Shell100.plugin">
      <ImagePath>bin\VisualStudio\v10.0</ImagePath>
    </PluginFile>
    <ConfigFile Include="Gallio.VisualStudio.Shell\Gallio.VisualStudio.Shell100.addin">
      <ImagePath>bin\VisualStudio\v10.0</ImagePath>
    </ConfigFile>
    
    <!--
    <AssemblyFile Include="Gallio.VisualStudio.Sail\bin\v10.0\Gallio.VisualStudio.Sail100.dll">
      <ImagePath>bin\VisualStudio\v10.0</ImagePath>
    </AssemblyFile>
    <PluginFile Include="Gallio.VisualStudio.Sail\Gallio.VisualStudio.Sail100.plugin">
      <ImagePath>bin\VisualStudio\v10.0</ImagePath>
    </PluginFile>
    -->
   
    <AssemblyFile Include="Gallio.VisualStudio.Tip\bin\v10.0\Gallio.VisualStudio.Tip100.dll">
      <ImagePath>bin\VisualStudio\v10.0</ImagePath>
    </AssemblyFile>
    <AssemblyFile Include="Gallio.VisualStudio.Tip.Proxy\bin\v10.0\Gallio.VisualStudio.Tip100.Proxy.dll">
      <ImagePath>bin\VisualStudio\v10.0</ImagePath>
    </AssemblyFile>
    <PluginFile Include="Gallio.VisualStudio.Tip\Gallio.VisualStudio.Tip100.plugin">
      <ImagePath>bin\VisualStudio\v10.0</ImagePath>
    </PluginFile>

    <TestAssembly Include="Gallio.VisualStudio.Shell.Tests\bin\v10.0\Gallio.VisualStudio.Shell100.Tests.dll" />
    <TestAssembly Include="Gallio.VisualStudio.Sail.Tests\bin\v10.0\Gallio.VisualStudio.Sail100.Tests.dll" />    
    <TestAssembly Include="Gallio.VisualStudio.Tip.Tests\bin\v10.0\Gallio.VisualStudio.Tip100.Tests.dll" />

    <Feature Include="FEATURE_VISUALSTUDIO" />
    <Feature Include="FEATURE_VISUALSTUDIO_100" />
    <Feature Include="FEATURE_VISUALSTUDIO_TIP_100" />
    <!-- Not ready for release.
    <Feature Include="FEATURE_VISUALSTUDIO_SAIL_100" />
    -->    
  </ItemGroup>
</Project>
