<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />
  <Import Project="VisualStudio.targets" />
  
  <ItemGroup Condition="$(VSIPInstalled)">
    <CSharpProject Include="Gallio.VisualStudio.Interop\Gallio.VisualStudio.Interop$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.VisualStudio.Interop.Tests\Gallio.VisualStudio.Interop.Tests$(ProjectVariant).csproj" />
    
    <PluginFile Include="Gallio.VisualStudio.Interop\Gallio.VisualStudio.Interop.plugin" />
    <Binary Include="Gallio.VisualStudio.Interop\bin\Gallio.VisualStudio.Interop.dll" />
    <Binary Include="Gallio.VisualStudio.Interop\bin\Gallio.VisualStudio.Interop.pdb" />

    <TestAssembly Include="Gallio.VisualStudio.Interop.Tests\bin\Gallio.VisualStudio.Interop.Tests.dll" />
  </ItemGroup>

  <Target Name="BeforeBuild">
    <Error Condition="! $(VSIPInstalled)"
           Text="VSIP packages must be installed to ensure that Gallio.VisualStudio.Interop component can be built.  This component is currently required for several features including navigate to source and debugging support.  Later it will be injected via the IoC." />
  </Target>
</Project>
