<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(RootDir)\bin\Module.targets" />
  <Import Project="VisualStudio90.targets" />
  <Import Project="VisualStudio100.targets" />
  
  <ItemGroup Condition="$(VSIP90Installed) or $(VSIP100Installed)">
    <CSharpProject Include="Gallio.VisualStudio.Shell.Common\Gallio.VisualStudio.Shell$(ProjectVariant).csproj" />

    <AssemblyFile Include="Gallio.VisualStudio.Shell.Common\bin\Gallio.VisualStudio.Shell.dll">
      <ImagePath>bin\VisualStudio</ImagePath>
    </AssemblyFile>
    <PdbFile Include="Gallio.VisualStudio.Shell.Common\bin\Gallio.VisualStudio.Shell.pdb">
      <ExcludeFromImage>true</ExcludeFromImage>
    </PdbFile>
    <PluginFile Include="Gallio.VisualStudio.Shell.Common\Gallio.VisualStudio.Shell.plugin">
      <ImagePath>bin\VisualStudio</ImagePath>
    </PluginFile>
  </ItemGroup>
</Project>
