<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />

  <ItemGroup>
    <CSharpProject Include="Gallio.Common.Splash\Gallio.Common.Splash$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.Common.Splash.Tests\Gallio.Common.Splash.Tests$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.Common.Splash.Demo\Gallio.Common.Splash.Demo$(ProjectVariant).csproj" />
    
    <AssemblyFile Include="Gallio.Common.Splash\bin\Gallio.Common.Splash.dll">
      <ImagePath>bin</ImagePath>
    </AssemblyFile>
    <PdbFile Include="Gallio.Common.Splash\bin\Gallio.Common.Splash.pdb">
      <ImagePath>bin</ImagePath>
    </PdbFile>
    <XmlDocFile Include="Gallio.Common.Splash\bin\Gallio.Common.Splash.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>

    <TestAssembly Include="Gallio.Common.Splash.Tests\bin\Gallio.Common.Splash.Tests.dll" />
  </ItemGroup>
</Project>
