<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <ItemGroup>
    <CSharpProject Include="Gallio.Common.Splash\Gallio.Common.Splash$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.Common.Splash.Tests\Gallio.Common.Splash.Tests$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.Common.Splash.Demo\Gallio.Common.Splash.Demo$(ProjectVariant).csproj" />
    
    <DocumentedAssembly Include="Gallio.Common.Splash\bin\Gallio.Common.Splash.dll" />

    <Binary Include="Gallio.Common.Splash\bin\Gallio.Common.Splash.dll" />
	
    <TestAssembly Include="Gallio.Common.Splash.Tests\bin\Gallio.Common.Splash.Tests.dll" />
  </ItemGroup>
</Project>
