<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.XunitAdapter\Gallio.XunitAdapter$(ProjectVariant).csproj" />

    <CSharpProject Include="Gallio.XunitAdapter.TestResources\Gallio.XunitAdapter.TestResources$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.XunitAdapter.Tests\Gallio.XunitAdapter.Tests$(ProjectVariant).csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.XunitAdapter\bin\Gallio.XunitAdapter.dll">
        <Folder>Xunit</Folder>
    </Binary>
    <PluginFile Include="Gallio.XunitAdapter\Gallio.XunitAdapter.plugin">
        <Folder>Xunit</Folder>
    </PluginFile>
    <Binary Include="Gallio.XunitAdapter\Readme.txt">
        <Folder>Xunit</Folder>
    </Binary>
    <Binary Include="libs\EULA.txt">
        <Folder>Xunit</Folder>
    </Binary>
    <Binary Include="libs\xunit.dll">
        <Folder>Xunit</Folder>
    </Binary>
    <Binary Include="libs\xunit.xml">
        <Folder>Xunit</Folder>
    </Binary>
    <Binary Include="libs\xunit.extensions.dll">
        <Folder>Xunit</Folder>
    </Binary>
    <Binary Include="libs\xunit.extensions.xml">
        <Folder>Xunit</Folder>
    </Binary>
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.XunitAdapter.Tests\bin\Gallio.XunitAdapter.Tests.dll" />
  </ItemGroup>
</Project>
