<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.XunitAdapter\Gallio.XunitAdapter$(ProjectVariant).csproj" />

    <CSharpProject Include="Gallio.XunitAdapter.TestResources\Gallio.XunitAdapter.TestResources$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.XunitAdapter.Tests\Gallio.XunitAdapter.Tests$(ProjectVariant).csproj" />
    
    <AssemblyFile Include="Gallio.XunitAdapter\bin\Gallio.XunitAdapter.dll">
      <ImagePath>bin\Xunit</ImagePath>
    </AssemblyFile>
    <PluginFile Include="Gallio.XunitAdapter\Gallio.XunitAdapter.plugin">
      <ImagePath>bin\Xunit</ImagePath>
    </PluginFile>
    <File Include="Gallio.XunitAdapter\xunit.dll.tdnet">
      <ImagePath>bin\Xunit</ImagePath>
    </File>
    <File Include="Gallio.XunitAdapter\Readme.txt">
      <ImagePath>bin\Xunit</ImagePath>
    </File>    
    <File Include="Gallio.XunitAdapter\Resources\xUnit.ico">
      <ImagePath>bin\Xunit\Resources</ImagePath>
    </File>
    
    <File Include="libs\EULA.txt">
      <ImagePath>bin\Xunit</ImagePath>
    </File>
    <File Include="libs\xunit.dll">
      <ImagePath>bin\Xunit</ImagePath>
    </File>
    <File Include="libs\xunit.xml">
      <ImagePath>bin\Xunit</ImagePath>
    </File>
    <File Include="libs\xunit.extensions.dll">
      <ImagePath>bin\Xunit</ImagePath>
    </File>
    <File Include="libs\xunit.extensions.xml">
      <ImagePath>bin\Xunit</ImagePath>
    </File>
    
    <TestAssembly Include="Gallio.XunitAdapter.Tests\bin\Gallio.XunitAdapter.Tests.dll" />
  </ItemGroup>
</Project>
