<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <CSharpProject Include="Gallio.XunitAdapter\Gallio.XunitAdapter.csproj" />

    <CSharpProject Include="Gallio.XunitAdapter.TestResources\Gallio.XunitAdapter.TestResources.csproj" />
    <CSharpProject Include="Gallio.XunitAdapter.Tests\Gallio.XunitAdapter.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.XunitAdapter\bin\Gallio.XunitAdapter.dll">
        <Folder>Xunit</Folder>
    </Binary>
    <Binary Include="Gallio.XunitAdapter\Gallio.XunitAdapter.plugin">
        <Folder>Xunit</Folder>
    </Binary>
    <Binary Include="Gallio.XunitAdapter\Readme.txt">
        <Folder>Xunit</Folder>
    </Binary>
    <Binary Include="libs\Xunit\EULA.txt">
        <Folder>Xunit</Folder>
    </Binary>
    <Binary Include="libs\Xunit\xunit.dll">
        <Folder>Xunit</Folder>
    </Binary>
    <Binary Include="libs\Xunit\xunit.xml">
        <Folder>Xunit</Folder>
    </Binary>
    <Binary Include="libs\Xunit\xunitext.dll">
        <Folder>Xunit</Folder>
    </Binary>
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.XunitAdapter.Tests\bin\Gallio.XunitAdapter.Tests.dll" />
  </ItemGroup>
</Project>
