<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(RootDir)\bin\Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.TeamCityIntegration\Gallio.TeamCityIntegration$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.TeamCityIntegration.Tests\Gallio.TeamCityIntegration.Tests$(ProjectVariant).csproj" />
    
    <AssemblyFile Include="Gallio.TeamCityIntegration\bin\Gallio.TeamCityIntegration.dll">
      <ImagePath>bin\TeamCity</ImagePath>
    </AssemblyFile>
    <PdbFile Include="Gallio.TeamCityIntegration\bin\Gallio.TeamCityIntegration.pdb">
      <ExcludeFromImage>true</ExcludeFromImage>
    </PdbFile>
    <PluginFile Include="Gallio.TeamCityIntegration\Gallio.TeamCityIntegration.plugin">
      <ImagePath>bin\TeamCity</ImagePath>
    </PluginFile>
    <File Include="Gallio.TeamCityIntegration\Readme.txt">
      <ImagePath>bin\TeamCity</ImagePath>
    </File>
    
    <File Include="Gallio.TeamCityIntegration\Resources\TeamCity.ico">
      <ImagePath>bin\TeamCity\Resources</ImagePath>
    </File>

    <TestAssembly Include="Gallio.TeamCityIntegration.Tests\bin\Gallio.TeamCityIntegration.Tests.dll" />
  </ItemGroup>
</Project>
