<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.NUnitAdapter\Gallio.NUnitAdapter$(ProjectVariant).csproj" />

    <CSharpProject Include="Gallio.NUnitAdapter.TestResources\Gallio.NUnitAdapter.TestResources$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.NUnitAdapter.Tests\Gallio.NUnitAdapter.Tests$(ProjectVariant).csproj" />    
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.NUnitAdapter\bin\Gallio.NUnitAdapter.dll">
        <Folder>NUnit</Folder>
    </Binary>
    <PluginFile Include="Gallio.NUnitAdapter\Gallio.NUnitAdapter.plugin">
        <Folder>NUnit</Folder>
    </PluginFile>
    <Binary Include="Gallio.NUnitAdapter\Readme.txt">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\license.txt">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\nunit.framework.dll">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\nunit.framework.extensions.dll">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\nunit.core.dll">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\nunit.core.extensions.dll">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\nunit.core.interfaces.dll">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\nunit.util.dll">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\addins\NUnit Addins Readme.txt">
        <Folder>NUnit\addins</Folder>
    </Binary>
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.NUnitAdapter.Tests\bin\Gallio.NUnitAdapter.Tests.dll" />
  </ItemGroup>
</Project>
