<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.NUnitAdapter\Gallio.NUnitAdapter25$(ProjectVariant).csproj" />

    <CSharpProject Include="Gallio.NUnitAdapter.TestResources\Gallio.NUnitAdapter25.TestResources$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.NUnitAdapter.Tests\Gallio.NUnitAdapter25.Tests$(ProjectVariant).csproj" />
    
    <AssemblyFile Include="Gallio.NUnitAdapter\bin\v2.5\Gallio.NUnitAdapter25.dll">
      <ImagePath>bin\NUnit\v2.5</ImagePath>
    </AssemblyFile>
    <PluginFile Include="Gallio.NUnitAdapter\Gallio.NUnitAdapter25.plugin">
      <ImagePath>bin\NUnit\v2.5</ImagePath>
    </PluginFile>
    <File Include="Gallio.NUnitAdapter\nunit.framework.dll.tdnet">
      <ImagePath>bin\NUnit\v2.5</ImagePath>
    </File>    
    <File Include="Gallio.NUnitAdapter\Readme.txt">
      <ImagePath>bin\NUnit\v2.5</ImagePath>
    </File>   
    <File Include="Gallio.NUnitAdapter\Resources\NUnit.ico">
      <ImagePath>bin\NUnit\v2.5\Resources</ImagePath>
    </File>
    
    <File Include="libs\v2.5\license.txt">
      <ImagePath>bin\NUnit\v2.5</ImagePath>
    </File>
    <File Include="libs\v2.5\nunit.framework.dll">
      <ImagePath>bin\NUnit\v2.5</ImagePath>
    </File>
    <File Include="libs\v2.5\nunit.framework.xml">
      <ImagePath>bin\NUnit\v2.5</ImagePath>
    </File>
    <File Include="libs\v2.5\nunit.core.dll">
      <ImagePath>bin\NUnit\v2.5</ImagePath>
    </File>
    <File Include="libs\v2.5\nunit.core.interfaces.dll">
      <ImagePath>bin\NUnit\v2.5</ImagePath>
    </File>
    <File Include="libs\v2.5\nunit.mocks.dll">
      <ImagePath>bin\NUnit\v2.5</ImagePath>
    </File>
    <File Include="libs\v2.5\nunit.util.dll">
      <ImagePath>bin\NUnit\v2.5</ImagePath>
    </File>
    <File Include="libs\v2.5\addins\NUnit Addins Readme.txt">
      <ImagePath>bin\NUnit\v2.5\addins</ImagePath>
    </File>
    
    <TestAssembly Include="Gallio.NUnitAdapter.Tests\bin\v2.5\Gallio.NUnitAdapter25.Tests.dll" />
    
    <Feature Include="FEATURE_NUNIT_ADAPTER_25" />
  </ItemGroup>
</Project>
