<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.NUnitAdapter\Gallio.NUnitAdapter248$(ProjectVariant).csproj" />

    <CSharpProject Include="Gallio.NUnitAdapter.TestResources\Gallio.NUnitAdapter248.TestResources$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.NUnitAdapter.Tests\Gallio.NUnitAdapter248.Tests$(ProjectVariant).csproj" />
    
    <AssemblyFile Include="Gallio.NUnitAdapter\bin\v2.4.8\Gallio.NUnitAdapter248.dll">
      <ImagePath>bin\NUnit\v2.4.8</ImagePath>
    </AssemblyFile>
    <PluginFile Include="Gallio.NUnitAdapter\Gallio.NUnitAdapter248.plugin">
      <ImagePath>bin\NUnit\v2.4.8</ImagePath>
    </PluginFile>
    <File Include="Gallio.NUnitAdapter\nunit.framework.dll.tdnet">
      <ImagePath>bin\NUnit\v2.4.8</ImagePath>
    </File>
    <File Include="Gallio.NUnitAdapter\Readme.txt">
      <ImagePath>bin\NUnit\v2.4.8</ImagePath>
    </File>    
    <File Include="Gallio.NUnitAdapter\Resources\NUnit.ico">
      <ImagePath>bin\NUnit\v2.4.8\Resources</ImagePath>
    </File>
    
    <File Include="libs\v2.4.8\license.txt">
      <ImagePath>bin\NUnit\v2.4.8</ImagePath>
    </File>
    <File Include="libs\v2.4.8\nunit.framework.dll">
      <ImagePath>bin\NUnit\v2.4.8</ImagePath>
    </File>
    <File Include="libs\v2.4.8\nunit.framework.extensions.dll">
      <ImagePath>bin\NUnit\v2.4.8</ImagePath>
    </File>
    <File Include="libs\v2.4.8\nunit.core.dll">
      <ImagePath>bin\NUnit\v2.4.8</ImagePath>
    </File>
    <File Include="libs\v2.4.8\nunit.core.extensions.dll">
      <ImagePath>bin\NUnit\v2.4.8</ImagePath>
    </File>
    <File Include="libs\v2.4.8\nunit.core.interfaces.dll">
      <ImagePath>bin\NUnit\v2.4.8</ImagePath>
    </File>
    <File Include="libs\v2.4.8\nunit.util.dll">
      <ImagePath>bin\NUnit\v2.4.8</ImagePath>
    </File>
    <File Include="libs\v2.4.8\addins\NUnit Addins Readme.txt">
      <ImagePath>bin\NUnit\v2.4.8\addins</ImagePath>
    </File>
    
    <TestAssembly Include="Gallio.NUnitAdapter.Tests\bin\v2.4.8\Gallio.NUnitAdapter248.Tests.dll" />
    
    <Feature Include="FEATURE_NUNIT_ADAPTER_248" />
  </ItemGroup>
</Project>
