<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(RootDir)\bin\Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.NUnitAdapter\Gallio.NUnitAdapter253$(ProjectVariant).csproj" />

    <CSharpProject Include="Gallio.NUnitAdapter.TestResources\Gallio.NUnitAdapter253.TestResources$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.NUnitAdapter.Tests\Gallio.NUnitAdapter253.Tests$(ProjectVariant).csproj" />
    
    <AssemblyFile Include="Gallio.NUnitAdapter\bin\v2.5.3\Gallio.NUnitAdapter253.dll">
      <ImagePath>bin\NUnit\v2.5.3</ImagePath>
    </AssemblyFile>
    <PdbFile Include="Gallio.NUnitAdapter\bin\v2.5.3\Gallio.NUnitAdapter253.pdb">
      <ExcludeFromImage>true</ExcludeFromImage>
    </PdbFile>
    <PluginFile Include="Gallio.NUnitAdapter\Gallio.NUnitAdapter253.plugin">
      <ImagePath>bin\NUnit\v2.5.3</ImagePath>
    </PluginFile>
    <File Include="Gallio.NUnitAdapter\nunit.framework.dll.tdnet">
      <ImagePath>bin\NUnit\v2.5.3</ImagePath>
    </File>    
    <File Include="Gallio.NUnitAdapter\Readme.txt">
      <ImagePath>bin\NUnit\v2.5.3</ImagePath>
    </File>   
    <File Include="Gallio.NUnitAdapter\Resources\NUnit.ico">
      <ImagePath>bin\NUnit\v2.5.3\Resources</ImagePath>
    </File>
    
    <File Include="libs\v2.5.3\license.txt">
      <ImagePath>bin\NUnit\v2.5.3</ImagePath>
    </File>
    <File Include="libs\v2.5.3\nunit.framework.dll">
      <ImagePath>bin\NUnit\v2.5.3</ImagePath>
    </File>
    <File Include="libs\v2.5.3\nunit.framework.xml">
      <ImagePath>bin\NUnit\v2.5.3</ImagePath>
    </File>
    <File Include="libs\v2.5.3\nunit.core.dll">
      <ImagePath>bin\NUnit\v2.5.3</ImagePath>
    </File>
    <File Include="libs\v2.5.3\nunit.core.interfaces.dll">
      <ImagePath>bin\NUnit\v2.5.3</ImagePath>
    </File>
    <File Include="libs\v2.5.3\nunit.mocks.dll">
      <ImagePath>bin\NUnit\v2.5.3</ImagePath>
    </File>
    <File Include="libs\v2.5.3\nunit.util.dll">
      <ImagePath>bin\NUnit\v2.5.3</ImagePath>
    </File>
    <File Include="libs\v2.5.3\addins\NUnit Addins Readme.txt">
      <ImagePath>bin\NUnit\v2.5.3\addins</ImagePath>
    </File>
    
    <TestAssembly Include="Gallio.NUnitAdapter.Tests\bin\v2.5.3\Gallio.NUnitAdapter253.Tests.dll" />
    
    <Feature Include="FEATURE_NUNIT_ADAPTER_253" />
  </ItemGroup>
</Project>
