<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(RootDir)\Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.NUnitAdapter\Gallio.NUnitAdapter.csproj" />

    <CSharpProject Include="Gallio.NUnitAdapter.TestResources\Gallio.NUnitAdapter.TestResources.csproj" />
    <CSharpProject Include="Gallio.NUnitAdapter.Tests\Gallio.NUnitAdapter.Tests.csproj" />    
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Gallio.NUnitAdapter\bin\Gallio.NUnitAdapter.dll">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="Gallio.NUnitAdapter\Gallio.NUnitAdapter.plugin">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="Gallio.NUnitAdapter\Readme.txt">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\license.txt">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\nunit.framework.dll">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\nunit.framework.extensions.dll">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\nunit.core.dll">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\nunit.core.extensions.dll">
        <Folder>NUnit</Folder>
    </Binary>
    <Binary Include="libs\nunit.core.interfaces.dll">
        <Folder>NUnit</Folder>
    </Binary>
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="Gallio.NUnitAdapter.Tests\bin\Gallio.NUnitAdapter.Tests.dll" />
  </ItemGroup>
</Project>
