@echo off

set ReSharperDir=C:\Program Files\JetBrains\ReSharper\v6.0\Bin

xcopy "%ReSharperDir%\JetBrains.Annotations.*" /y
xcopy "%ReSharperDir%\JetBrains.Platform.CommonServices.*" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.AbstractTreeBuilder.*" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.ActionManagement.*" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.ActivityTracking.*" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.ComponentModel.*" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.DocumentManager.*" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.DocumentModel.*" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.IDE.*" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.Interop.WinApi.*" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.Metadata.*" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.ProjectModel.dll" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.ProjectModel.xml" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.Satellite.exe" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.Satellite.xml" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.Shell.dll" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.Shell.xml" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.TextControl.dll" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.TextControl.xml" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.UI.Avalon.dll" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.UI.Avalon.xml" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.UI.dll" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.UI.xml" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.Util.dll" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.Util.xml" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.VSIntegration.dll" /y
xcopy "%ReSharperDir%\JetBrains.Platform.ReSharper.VSIntegration.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Daemon.CSharp.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Daemon.CSharp.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Daemon.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Daemon.Specific.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Daemon.Specific.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Daemon.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.ExternalProcessStorage.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.ExternalProcessStorage.Process.exe" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.ExternalProcessStorage.Process.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.ExternalProcessStorage.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Feature.Services.CSharp.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Feature.Services.CSharp.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Feature.Services.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Feature.Services.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Altering.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Altering.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Browsing.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Browsing.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Common.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Common.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Environment.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Environment.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Finding.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Finding.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Intellisense.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Intellisense.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Internal.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Features.Internal.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Intentions.CSharp.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Intentions.CSharp.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Intentions.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Intentions.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.LiveTemplates.CSharp.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.LiveTemplates.CSharp.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.LiveTemplates.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.LiveTemplates.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.NewRefactorings.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.NewRefactorings.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Psi.CSharp.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Psi.CSharp.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Psi.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Psi.Services.CSharp.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Psi.Services.CSharp.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Psi.Services.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Psi.Services.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Psi.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Psi.Xml.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Psi.Xml.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Refactorings.CSharp.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Refactorings.CSharp.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Resources.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.Resources.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.SolutionAnalysis.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.SolutionAnalysis.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.SolutionBuilder.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.SolutionBuilder.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.TaskRunner.exe" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.TaskRunner.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.TaskRunnerFramework.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.TaskRunnerFramework.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.TestFramework.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.TestFramework.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.TodoExplorer.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.TodoExplorer.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.UnitTestExplorer.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.UnitTestExplorer.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.UnitTestFramework.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.UnitTestFramework.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.VS.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.VS.xml" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.VSI.dll" /y
xcopy "%ReSharperDir%\JetBrains.ReSharper.VSI.xml" /y