//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gallio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter list already contains a parameter named &apos;{0}&apos;..
        /// </summary>
        internal static string BaseTest_ParameterListAlreadyContainsParameterWithSameName {
            get {
                return ResourceManager.GetString("BaseTest_ParameterListAlreadyContainsParameterWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test to be added is already a child of another test..
        /// </summary>
        internal static string BaseTest_TestAlreadyHasAParent {
            get {
                return ResourceManager.GetString("BaseTest_TestAlreadyHasAParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; of .
        /// </summary>
        internal static string CodeReference_ToString_ParameterName {
            get {
                return ResourceManager.GetString("CodeReference_ToString_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection arguments must have AllowMultiple flag..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_CollectionArgumentsMustAllowMultipleValues {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_CollectionArgumentsMustAllowMultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate &apos;{0}&apos; argument..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_DuplicateArgument {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_DuplicateArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate &apos;{0}&apos; argument value &apos;{1}&apos;, expected unique values..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_DuplicateArgumentValueExpectedUnique {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_DuplicateArgumentValueExpectedUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;{0}&apos; argument value &apos;{1}&apos;..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_InvalidArgumentValue {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_InvalidArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique flag only applicable to collection arguments..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_InvalidUsageOfUniqueFlag {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_InvalidUsageOfUniqueFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument long name must be specified..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_MissingLongName {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_MissingLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required argument &apos;/{0}&apos;..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_MissingRequiredArgument {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_MissingRequiredArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required default argument..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_MissingRequiredDefaultArgument {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_MissingRequiredDefaultArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported value type..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_UnsupportedValueType {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_UnsupportedValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed argument object is not of the correct type..
        /// </summary>
        internal static string CommandLineArgumentParser_ArgumentObjectIsOfIncorrectType {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ArgumentObjectIsOfIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate argument name &apos;{0}&apos;..
        /// </summary>
        internal static string CommandLineArgumentParser_DuplicateArgumentName {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_DuplicateArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening response file &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string CommandLineArgumentParser_ErrorOpeningResponseFile {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ErrorOpeningResponseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal exception occurred while parsing arguments: {0}.
        /// </summary>
        internal static string CommandLineArgumentParser_ExceptionWhileParsing {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ExceptionWhileParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched quotes in response file &apos;{0}&apos;.
        /// </summary>
        internal static string CommandLineArgumentParser_MismatchedQuotedInResponseFile {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_MismatchedQuotedInResponseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one default command line argument has been defined..
        /// </summary>
        internal static string CommandLineArgumentParser_MoreThanOneDefaultCommandLineArgumentDefined {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_MoreThanOneDefaultCommandLineArgumentDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fields tagged with CommandLineArgumentAttribute..
        /// </summary>
        internal static string CommandLineArgumentParser_NoArgumentFields {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_NoArgumentFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read response file for more options..
        /// </summary>
        internal static string CommandLineArgumentParser_ResponseFileDescription {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ResponseFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response file &apos;0&apos; does not exist..
        /// </summary>
        internal static string CommandLineArgumentParser_ResponseFileDoesNotExist {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ResponseFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string CommandLineArgumentParser_ResponseFileValueLabel {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ResponseFileValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized argument &apos;{0}&apos;..
        /// </summary>
        internal static string CommandLineArgumentParser_UnrecognizedArgument {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_UnrecognizedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The available options are: .
        /// </summary>
        internal static string CommandLineOutput_AvailableOptions {
            get {
                return ResourceManager.GetString("CommandLineOutput_AvailableOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Short form: {0}).
        /// </summary>
        internal static string CommandLineOutput_ShortForm {
            get {
                return ResourceManager.GetString("CommandLineOutput_ShortForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Version {1}.{2}.{3} build {4}.
        /// </summary>
        internal static string ConsoleProgram_ApplicationTitleFormat {
            get {
                return ResourceManager.GetString("ConsoleProgram_ApplicationTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- CANCELED ---.
        /// </summary>
        internal static string ConsoleProgressMonitor_CanceledBanner {
            get {
                return ResourceManager.GetString("ConsoleProgressMonitor_CanceledBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt; CANCELING &lt;&lt;&lt;.
        /// </summary>
        internal static string ConsoleProgressMonitor_CancelingBanner {
            get {
                return ResourceManager.GetString("ConsoleProgressMonitor_CancelingBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The runtime could not be initialized..
        /// </summary>
        internal static string DefaultRuntime_RuntimeCannotBeInitialized {
            get {
                return ResourceManager.GetString("DefaultRuntime_RuntimeCannotBeInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot escape character {0}.
        /// </summary>
        internal static string FilterParser_CannotEscapeCharacter {
            get {
                return ResourceManager.GetString("FilterParser_CannotEscapeCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (char code = {0}).
        /// </summary>
        internal static string FilterParser_CharCode {
            get {
                return ResourceManager.GetString("FilterParser_CharCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon expected.
        /// </summary>
        internal static string FilterParser_ColonExpected {
            get {
                return ResourceManager.GetString("FilterParser_ColonExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma expected.
        /// </summary>
        internal static string FilterParser_CommaExpected {
            get {
                return ResourceManager.GetString("FilterParser_CommaExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter expression can&apos;t be empty.
        /// </summary>
        internal static string FilterParser_EmptyFilterError {
            get {
                return ResourceManager.GetString("FilterParser_EmptyFilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing end {0}.
        /// </summary>
        internal static string FilterParser_MissingEndDelimiter {
            get {
                return ResourceManager.GetString("FilterParser_MissingEndDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing escaped character.
        /// </summary>
        internal static string FilterParser_MissingEscapedCharacter {
            get {
                return ResourceManager.GetString("FilterParser_MissingEscapedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right bracket expected.
        /// </summary>
        internal static string FilterParser_RightBracketExpected {
            get {
                return ResourceManager.GetString("FilterParser_RightBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String literal expected.
        /// </summary>
        internal static string FilterParser_StringLiteralExpected {
            get {
                return ResourceManager.GetString("FilterParser_StringLiteralExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character found ({0}).
        /// </summary>
        internal static string FilterParser_UnexpectedCharacterFound {
            get {
                return ResourceManager.GetString("FilterParser_UnexpectedCharacterFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of input.
        /// </summary>
        internal static string FilterParser_UnexpectedEndOfInput {
            get {
                return ResourceManager.GetString("FilterParser_UnexpectedEndOfInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected.
        /// </summary>
        internal static string FilterParser_ValueExpected {
            get {
                return ResourceManager.GetString("FilterParser_ValueExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a method with signature ({0}) but found ({1})..
        /// </summary>
        internal static string ModelUtils_InvalidSignature {
            get {
                return ResourceManager.GetString("ModelUtils_InvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote host service threw an exception or could not be reached..
        /// </summary>
        internal static string RemoteHost_RemoteException {
            get {
                return ResourceManager.GetString("RemoteHost_RemoteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string RootTest_RootTestName {
            get {
                return ResourceManager.GetString("RootTest_RootTestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At most one action may be active within the scope at a time..
        /// </summary>
        internal static string ThreadAbortScope_ReentranceException {
            get {
                return ResourceManager.GetString("ThreadAbortScope_ReentranceException", resourceCulture);
            }
        }
    }
}
