//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gallio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string BaseStep_RootStepName {
            get {
                return ResourceManager.GetString("BaseStep_RootStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter list already contains a parameter named &apos;{0}&apos;..
        /// </summary>
        internal static string BaseTemplate_ParameterListAlreadyContainsParameterWithSameName {
            get {
                return ResourceManager.GetString("BaseTemplate_ParameterListAlreadyContainsParameterWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of template arguments for template &apos;{0}&apos;, expected {1} but received {2}..
        /// </summary>
        internal static string BaseTemplateBinding_InvalidNumberOfTemplateArguments {
            get {
                return ResourceManager.GetString("BaseTemplateBinding_InvalidNumberOfTemplateArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing argument for template parameter &apos;{0}&apos; of template &apos;{1}&apos;..
        /// </summary>
        internal static string BaseTemplateBinding_MissingArgumentForTemplateParameter {
            get {
                return ResourceManager.GetString("BaseTemplateBinding_MissingArgumentForTemplateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; of .
        /// </summary>
        internal static string CodeReference_ToString_ParameterName {
            get {
                return ResourceManager.GetString("CodeReference_ToString_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection arguments must have AllowMultiple flag..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_CollectionArgumentsMustAllowMultipleValues {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_CollectionArgumentsMustAllowMultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate &apos;{0}&apos; argument..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_DuplicateArgument {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_DuplicateArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate &apos;{0}&apos; argument value &apos;{1}&apos;, expected unique values..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_DuplicateArgumentValueExpectedUnique {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_DuplicateArgumentValueExpectedUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;{0}&apos; argument value &apos;{1}&apos;..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_InvalidArgumentValue {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_InvalidArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique flag only applicable to collection arguments..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_InvalidUsageOfUniqueFlag {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_InvalidUsageOfUniqueFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument long name must be specified..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_MissingLongName {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_MissingLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required argument &apos;/{0}&apos;..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_MissingRequiredArgument {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_MissingRequiredArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required default argument..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_MissingRequiredDefaultArgument {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_MissingRequiredDefaultArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported value type..
        /// </summary>
        internal static string CommandLineArgumentParser_Argument_UnsupportedValueType {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_Argument_UnsupportedValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed argument object is not of the correct type..
        /// </summary>
        internal static string CommandLineArgumentParser_ArgumentObjectIsOfIncorrectType {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ArgumentObjectIsOfIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate argument name &apos;{0}&apos;..
        /// </summary>
        internal static string CommandLineArgumentParser_DuplicateArgumentName {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_DuplicateArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening response file &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string CommandLineArgumentParser_ErrorOpeningResponseFile {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ErrorOpeningResponseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal exception occurred while parsing arguments: {0}.
        /// </summary>
        internal static string CommandLineArgumentParser_ExceptionWhileParsing {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ExceptionWhileParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched quotes in response file &apos;{0}&apos;.
        /// </summary>
        internal static string CommandLineArgumentParser_MismatchedQuotedInResponseFile {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_MismatchedQuotedInResponseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one default command line argument has been defined..
        /// </summary>
        internal static string CommandLineArgumentParser_MoreThanOneDefaultCommandLineArgumentDefined {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_MoreThanOneDefaultCommandLineArgumentDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fields tagged with CommandLineArgumentAttribute..
        /// </summary>
        internal static string CommandLineArgumentParser_NoArgumentFields {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_NoArgumentFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read response file for more options..
        /// </summary>
        internal static string CommandLineArgumentParser_ResponseFileDescription {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ResponseFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response file &apos;0&apos; does not exist..
        /// </summary>
        internal static string CommandLineArgumentParser_ResponseFileDoesNotExist {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ResponseFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string CommandLineArgumentParser_ResponseFileValueLabel {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ResponseFileValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized argument &apos;{0}&apos;..
        /// </summary>
        internal static string CommandLineArgumentParser_UnrecognizedArgument {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_UnrecognizedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The available options are: .
        /// </summary>
        internal static string CommandLineOutput_AvailableOptions {
            get {
                return ResourceManager.GetString("CommandLineOutput_AvailableOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Short form: {0}).
        /// </summary>
        internal static string CommandLineOutput_ShortForm {
            get {
                return ResourceManager.GetString("CommandLineOutput_ShortForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- CANCELED ---.
        /// </summary>
        internal static string ConsoleProgressMonitor_CanceledBanner {
            get {
                return ResourceManager.GetString("ConsoleProgressMonitor_CanceledBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt; CANCELING &lt;&lt;&lt;.
        /// </summary>
        internal static string ConsoleProgressMonitor_CancelingBanner {
            get {
                return ResourceManager.GetString("ConsoleProgressMonitor_CancelingBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Execution Log: Attach ({0})]
        ///	Attachment Name:         {1}
        ///	Attachment Content Type: {2}.
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_Attach_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_Attach_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Execution Log: Begin Section ({0})]
        ///	Stream Name:  {1}
        ///	Section Name: {2}.
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_BeginSection_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_BeginSection_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Execution Log: Embed Existing ({0})]
        ///	Stream Name:     {1}
        ///	Attachment Name: {2}.
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_EmbedExisting_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_EmbedExisting_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Execution Log: End Section ({0})]
        ///	Stream Name: {1}.
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_EndSection_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_EndSection_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Execution Log: Write ({0})]
        ///	Stream Name: {1}
        ///	Text:        {2}.
        /// </summary>
        internal static string DebugMonitor_ExecutionLogEvent_Write_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_ExecutionLogEvent_Write_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lifecycle: Add Metadata ({0})]
        ///	Metadata Key:   {1}
        ///	Metadata Value: {2}.
        /// </summary>
        internal static string DebugMonitor_LifecycleEvent_AddMetadata_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_LifecycleEvent_AddMetadata_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lifecycle: Finish ({0})]
        ///	State:    {1}
        ///	Outcome:  {2}
        ///	Asserts:  {3}
        ///	Duration: {4:0.000}s.
        /// </summary>
        internal static string DebugMonitor_LifecycleEvent_Finish_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_LifecycleEvent_Finish_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lifecycle: Set Phase ({0})]
        ///	Phase Name: {1}.
        /// </summary>
        internal static string DebugMonitor_LifecycleEvent_SetPhase_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_LifecycleEvent_SetPhase_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lifecycle: Start ({0})].
        /// </summary>
        internal static string DebugMonitor_LifecycleEvent_Start_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_LifecycleEvent_Start_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Message: {0}] - {1}.
        /// </summary>
        internal static string DebugMonitor_MessageEvent_EventFormat {
            get {
                return ResourceManager.GetString("DebugMonitor_MessageEvent_EventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}.
        /// </summary>
        internal static string LogMonitor_HeaderFormat {
            get {
                return ResourceManager.GetString("LogMonitor_HeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canceled.
        /// </summary>
        internal static string LogMonitor_Status_Canceled {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string LogMonitor_Status_Error {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        internal static string LogMonitor_Status_Failed {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ignored.
        /// </summary>
        internal static string LogMonitor_Status_Ignored {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inconclusive.
        /// </summary>
        internal static string LogMonitor_Status_Inconclusive {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Inconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not run.
        /// </summary>
        internal static string LogMonitor_Status_NotRun {
            get {
                return ResourceManager.GetString("LogMonitor_Status_NotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passed.
        /// </summary>
        internal static string LogMonitor_Status_Passed {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skipped.
        /// </summary>
        internal static string LogMonitor_Status_Skipped {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting.
        /// </summary>
        internal static string LogMonitor_Status_Starting {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string LogMonitor_Status_Unknown {
            get {
                return ResourceManager.GetString("LogMonitor_Status_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a method with signature ({0}) but found ({1})..
        /// </summary>
        internal static string ModelUtils_InvalidSignature {
            get {
                return ResourceManager.GetString("ModelUtils_InvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node to be added is already a child of another node..
        /// </summary>
        internal static string ModelUtils_NodeAlreadyHasAParent {
            get {
                return ResourceManager.GetString("ModelUtils_NodeAlreadyHasAParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string RootTemplate_RootTemplateName {
            get {
                return ResourceManager.GetString("RootTemplate_RootTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string RootTest_RootTestName {
            get {
                return ResourceManager.GetString("RootTest_RootTestName", resourceCulture);
            }
        }
    }
}
