<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  <Import Project="ReSharper41.targets" />

  <PropertyGroup>
    <MonoCompatible>false</MonoCompatible>
  </PropertyGroup>

  <ItemGroup Condition="$(ReSharper41Installed)">
    <CSharpProject Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner41$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.ReSharperRunner.Tests\Gallio.ReSharperRunner41.Tests$(ProjectVariant).csproj" />

    <Binary Include="Gallio.ReSharperRunner\bin\v4.1\Gallio.ReSharperRunner41.dll">
      <Folder>ReSharper\v4.1</Folder>
    </Binary>

    <TestAssembly Include="Gallio.ReSharperRunner.Tests\bin\v4.1\Gallio.ReSharperRunner41.Tests.dll" />

    <Feature Include="FEATURE_RESHARPER_RUNNER_41" />
  </ItemGroup>
</Project>
