<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(RootDir)\bin\Module.targets" />
  <Import Project="ReSharper50.targets" />

  <ItemGroup Condition="$(ReSharper50Installed)">
    <CSharpProject Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner50$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.ReSharperRunner.Tests\Gallio.ReSharperRunner50.Tests$(ProjectVariant).csproj" />

    <PluginFile Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner50.plugin">
      <ImagePath>bin\ReSharper\v5.0</ImagePath>
    </PluginFile>
    <AssemblyFile Include="Gallio.ReSharperRunner\bin\v5.0\Gallio.ReSharperRunner50.dll">
      <ImagePath>bin\ReSharper\v5.0</ImagePath>
    </AssemblyFile>
    <PdbFile Include="Gallio.ReSharperRunner\bin\v5.0\Gallio.ReSharperRunner50.pdb">
      <ExcludeFromImage>true</ExcludeFromImage>
    </PdbFile>

    <File Include="Gallio.ReSharperRunner\Resources\resharper.ico">
      <ImagePath>bin\ReSharper\v5.0\Resources</ImagePath>
    </File>

	<!--
    <TestAssembly Include="Gallio.ReSharperRunner.Tests\bin\v5.0\Gallio.ReSharperRunner50.Tests.dll" />
	-->

    <Feature Include="FEATURE_RESHARPER_RUNNER" />
    <Feature Include="FEATURE_RESHARPER_RUNNER_50" />
  </ItemGroup>
</Project>
