<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />
  <Import Project="ReSharper45.targets" />

  <ItemGroup Condition="$(ReSharper45Installed)">
    <CSharpProject Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner45$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.ReSharperRunner.Tests\Gallio.ReSharperRunner45.Tests$(ProjectVariant).csproj" />

    <PluginFile Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner45.plugin">
      <Folder>ReSharper\v4.5</Folder>
    </PluginFile>
    <Binary Include="Gallio.ReSharperRunner\bin\v4.5\Gallio.ReSharperRunner45.dll">
      <Folder>ReSharper\v4.5</Folder>
    </Binary>

    <TestAssembly Include="Gallio.ReSharperRunner.Tests\bin\v4.5\Gallio.ReSharperRunner45.Tests.dll" />

    <Feature Include="FEATURE_RESHARPER_RUNNER_45" />
  </ItemGroup>
</Project>
