<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />
  <Import Project="ReSharper50.targets" />

  <ItemGroup Condition="$(ReSharper50Installed)">
    <CSharpProject Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner50$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.ReSharperRunner.Tests\Gallio.ReSharperRunner50.Tests$(ProjectVariant).csproj" />

    <PluginFile Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner50.plugin">
      <Folder>ReSharper\v5.0</Folder>
    </PluginFile>
    <Binary Include="Gallio.ReSharperRunner\bin\v5.0\Gallio.ReSharperRunner50.dll">
      <Folder>ReSharper\v5.0</Folder>
    </Binary>

	<!--
    <TestAssembly Include="Gallio.ReSharperRunner.Tests\bin\v5.0\Gallio.ReSharperRunner50.Tests.dll" />
	-->

    <Feature Include="FEATURE_RESHARPER_RUNNER_50" />
  </ItemGroup>
</Project>
