<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />
  <Import Project="ReSharper31.targets" />

  <ItemGroup Condition="$(ReSharper31Installed)">
    <CSharpProject Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner31$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.ReSharperRunner.Tests\Gallio.ReSharperRunner31.Tests$(ProjectVariant).csproj" />

    <PluginFile Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner31.plugin">
      <Folder>ReSharper\v3.1</Folder>
    </PluginFile>
    <Binary Include="Gallio.ReSharperRunner\bin\v3.1\Gallio.ReSharperRunner31.dll">
      <Folder>ReSharper\v3.1</Folder>
    </Binary>

    <TestAssembly Include="Gallio.ReSharperRunner.Tests\bin\v3.1\Gallio.ReSharperRunner31.Tests.dll" />

    <Feature Include="FEATURE_RESHARPER_RUNNER_31" />
  </ItemGroup>
</Project>

