<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(RootDir)\bin\Module.targets" />
  <Import Project="ReSharper45.targets" />

  <ItemGroup Condition="$(ReSharper45Installed)">
    <CSharpProject Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner45$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.ReSharperRunner.Tests\Gallio.ReSharperRunner45.Tests$(ProjectVariant).csproj" />

    <PluginFile Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner45.plugin">
      <ImagePath>bin\ReSharper\v4.5</ImagePath>
    </PluginFile>
    <AssemblyFile Include="Gallio.ReSharperRunner\bin\v4.5\Gallio.ReSharperRunner45.dll">
      <ImagePath>bin\ReSharper\v4.5</ImagePath>
    </AssemblyFile>
    <PdbFile Include="Gallio.ReSharperRunner\bin\v4.5\Gallio.ReSharperRunner45.pdb">
      <ExcludeFromImage>true</ExcludeFromImage>
    </PdbFile>

    <File Include="Gallio.ReSharperRunner\Resources\resharper.ico">
      <ImagePath>bin\ReSharper\v4.5\Resources</ImagePath>
    </File>

<!--
    <TestAssembly Include="Gallio.ReSharperRunner.Tests\bin\v4.5\Gallio.ReSharperRunner45.Tests.dll" />
-->

    <Feature Include="FEATURE_RESHARPER_RUNNER" />
    <Feature Include="FEATURE_RESHARPER_RUNNER_45" />
  </ItemGroup>
</Project>
