<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  <Import Project="ReSharper40.targets" />

  <PropertyGroup>
    <MonoCompatible>false</MonoCompatible>
  </PropertyGroup>

  <ItemGroup Condition="$(ReSharper40Installed)">
    <CSharpProject Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner40$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.ReSharperRunner.Tests\Gallio.ReSharperRunner40.Tests$(ProjectVariant).csproj" />

    <Binary Include="Gallio.ReSharperRunner\bin\v4.0\Gallio.ReSharperRunner40.dll">
      <Folder>ReSharper\v4.0</Folder>
    </Binary>

    <TestAssembly Include="Gallio.ReSharperRunner.Tests\bin\v4.0\Gallio.ReSharperRunner40.Tests.dll" />

    <Feature Include="FEATURE_RESHARPER_RUNNER_40" />
  </ItemGroup>
</Project>
