<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(RootDir)\Module.targets" />
  <Import Project="ReSharper.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner.csproj" />
    <CSharpProject Include="Gallio.ReSharperRunner.Tests\Gallio.ReSharperRunner.Tests.csproj" />
  </ItemGroup>

  <Choose>
    <When Condition="$(ReSharperInstalled)">
      <ItemGroup>
        <Binary Include="Gallio.ReSharperRunner\bin\Gallio.ReSharperRunner.dll" />
        <Binary Include="Gallio.ReSharperRunner\bin\Gallio.ReSharperRunner.dll.config" />
      </ItemGroup>

      <ItemGroup>
        <TestAssembly Include="Gallio.ReSharperRunner.Tests\bin\Gallio.ReSharperRunner.Tests.dll" />
      </ItemGroup>
    </When>
  </Choose>
</Project>
