<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />
  <Import Project="ReSharper41.targets" />

  <ItemGroup Condition="$(ReSharper41Installed)">
    <CSharpProject Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner41$(ProjectVariant).csproj" />
    <CSharpProject Include="Gallio.ReSharperRunner.Tests\Gallio.ReSharperRunner41.Tests$(ProjectVariant).csproj" />

    <PluginFile Include="Gallio.ReSharperRunner\Gallio.ReSharperRunner41.plugin">
      <ImagePath>bin\ReSharper\v4.1</ImagePath>
    </PluginFile>
    <AssemblyFile Include="Gallio.ReSharperRunner\bin\v4.1\Gallio.ReSharperRunner41.dll">
      <ImagePath>bin\ReSharper\v4.1</ImagePath>
    </AssemblyFile>

    <TestAssembly Include="Gallio.ReSharperRunner.Tests\bin\v4.1\Gallio.ReSharperRunner41.Tests.dll" />

    <Feature Include="FEATURE_RESHARPER_RUNNER" />
    <Feature Include="FEATURE_RESHARPER_RUNNER_41" />
  </ItemGroup>
</Project>
