<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(ModuleTargets)" />
  <Import Project="ReSharper31.targets" />
  <Import Project="ReSharper40.targets" />
  <Import Project="ReSharper41.targets" />
  <Import Project="ReSharper45.targets" />
  <Import Project="ReSharper50.targets" />

  <ItemGroup Condition="$(ReSharper31Installed) or $(ReSharper40Installed) or $(ReSharper41Installed) or $(ReSharper45Installed) or $(ReSharper50Installed)">
    <Feature Include="FEATURE_RESHARPER_RUNNER" />
  </ItemGroup>
</Project>
